export type ComingSoonCourse = {
  slug: string;
  title: string;
  description: string;
  icon: string;
  category: string;
  badge?: string;
  totalLessons: number;
  totalXp: number;
  level: string;
};

export const comingSoonCourses: ComingSoonCourse[] = [
  {
    slug: "chatgpt-lil-amal",
    title: "ChatGPT للأعمال",
    description: "أتقن ChatGPT عشان توفر وقتك، تتواصل أحسن، وتنمّي شغلك.",
    icon: "💬",
    category: "الأعمال",
    badge: "أعمال",
    totalLessons: 21,
    totalXp: 420,
    level: "مبتدئ",
  },
  {
    slug: "claude-fakker-bezaka",
    title: "Claude AI: فكّر بذكاء، اشتغل بسرعة",
    description: "من مبتدئ تمامًا لمستخدم واثق لـ Claude في ٢١ درس.",
    icon: "🧠",
    category: "أدوات الذكاء الاصطناعي",
    badge: "جديد",
    totalLessons: 21,
    totalXp: 420,
    level: "مبتدئ",
  },
  {
    slug: "itqan-gemini",
    title: "إتقان Gemini: قوة جوجل الذكية",
    description: "من أول برومبت لسير عمل متقدم — افتح قوة أدوات جوجل الذكية بالكامل.",
    icon: "✨",
    category: "أدوات الذكاء الاصطناعي",
    badge: "شائع",
    totalLessons: 21,
    totalXp: 420,
    level: "مبتدئ",
  },
  {
    slug: "claude-excel",
    title: "إتقان Claude لإكسل",
    description: "استخدم الذكاء الاصطناعي تفهم وتصلح وتبني ملفات إكسل — من غير مهارات متقدمة.",
    icon: "📊",
    category: "أدوات الذكاء الاصطناعي",
    badge: "جديد",
    totalLessons: 15,
    totalXp: 375,
    level: "مبتدئ",
  },
  {
    slug: "ai-powerpoint",
    title: "إتقان الذكاء الاصطناعي للعروض التقديمية",
    description: "خطط وابنِ وقدّم عروض تقديمية فعلًا مؤثرة — من غير مهارات تصميم.",
    icon: "📽️",
    category: "أدوات الذكاء الاصطناعي",
    badge: "جديد",
    totalLessons: 18,
    totalXp: 450,
    level: "مبتدئ",
  },
  {
    slug: "ai-microsoft-365",
    title: "الذكاء الاصطناعي لمايكروسوفت 365",
    description: "استخدم الذكاء الاصطناعي في Word و Excel و PowerPoint و Outlook و Teams عشان تخلّص شغلك أسرع.",
    icon: "🗂️",
    category: "أدوات الذكاء الاصطناعي",
    badge: "جديد",
    totalLessons: 24,
    totalXp: 600,
    level: "متوسط",
  },
  {
    slug: "itqan-handasat-elprompt",
    title: "إتقان هندسة البرومبت",
    description: "اكتب برومبتات بتديك نتايج مضبوطة في كل مرة.",
    icon: "✍️",
    category: "أدوات الذكاء الاصطناعي",
    badge: "أساسي",
    totalLessons: 21,
    totalXp: 420,
    level: "مبتدئ",
  },
  {
    slug: "nizam-el-entaj",
    title: "نظام الإنتاجية الذكي",
    description: "خلّص ضعف شغلك في نص الوقت — ابنِ نظام إنتاجية بالذكاء الاصطناعي.",
    icon: "⚡",
    category: "الأعمال",
    badge: "إنتاجية",
    totalLessons: 21,
    totalXp: 525,
    level: "متوسط",
  },
  {
    slug: "mokhattat-automation",
    title: "مخطط أتمتة الذكاء الاصطناعي",
    description: "أتمت المهام المتكررة ووفر ساعات يوميًا بسير عمل ذكي بدون كود.",
    icon: "🤖",
    category: "أدوات الذكاء الاصطناعي",
    badge: "أتمتة",
    totalLessons: 28,
    totalXp: 700,
    level: "متوسط",
  },
  {
    slug: "mosare3-sane3-el-mohtwa",
    title: "مسرّع صانع المحتوى بالذكاء الاصطناعي",
    description: "استخدم الذكاء الاصطناعي تكتب وتصمم وتنشر محتوى أسرع بـ١٠ مرات.",
    icon: "🎬",
    category: "صنّاع المحتوى",
    badge: "صنّاع محتوى",
    totalLessons: 21,
    totalXp: 420,
    level: "متوسط",
  },
  {
    slug: "mosare3-el-dakhl",
    title: "مسرّع الدخل الجانبي بالذكاء الاصطناعي",
    description: "٧ مصادر دخل مجرّبة بالذكاء الاصطناعي — أطلق أول واحدة في ٤٨ ساعة.",
    icon: "💸",
    category: "الأعمال",
    badge: "دخل جانبي",
    totalLessons: 21,
    totalXp: 630,
    level: "متوسط",
  },
  {
    slug: "48-hour-launch",
    title: "إطلاق منتج رقمي في ٤٨ ساعة",
    description: "من الفكرة لأول عملية بيع في عطلة أسبوع واحدة.",
    icon: "🚀",
    category: "الأعمال",
    badge: "سبرينت",
    totalLessons: 21,
    totalXp: 525,
    level: "متوسط",
  },
  {
    slug: "mosare3-el-e3lanat",
    title: "مسرّع إعلانات الذكاء الاصطناعي",
    description: "اكتب نصوص إعلانية، ولّد تصميمات، وحسّن حملاتك بالذكاء الاصطناعي.",
    icon: "📣",
    category: "الأعمال",
    badge: "إعلانات",
    totalLessons: 21,
    totalXp: 525,
    level: "متقدم",
  },
  {
    slug: "estodio-el-aflam",
    title: "استوديو الأفلام بالذكاء الاصطناعي",
    description: "اصنع أفلام قصيرة وفيديوهات علامتك التجارية بأدوات الفيديو الذكية — من غير كاميرا.",
    icon: "🎥",
    category: "صنّاع المحتوى",
    badge: "مميز",
    totalLessons: 21,
    totalXp: 525,
    level: "متقدم",
  },
];

export const explorePaths = [
  { key: "success-mindset", title: "نمط النجاح", icon: "🧠", coursesCount: 6 },
  { key: "career-growth", title: "النمو المهني", icon: "💼", coursesCount: 5 },
  { key: "business", title: "الأعمال", icon: "📈", coursesCount: 6 },
  { key: "health-energy", title: "الصحة والطاقة", icon: "💪", coursesCount: 4 },
];

export const catalogSections = [
  { title: "إتقان أدوات الذكاء الاصطناعي", description: "كورسات متعمقة في أقوى أدوات الذكاء الاصطناعي", icon: "⚡", coursesCount: 9 },
  { title: "الذكاء الاصطناعي للأعمال", description: "غيّر طريقة شغلك وقيادتك ونموّك بالذكاء الاصطناعي", icon: "📈", coursesCount: 6 },
  { title: "الذكاء الاصطناعي لصنّاع المحتوى", description: "أنتج أكتر وأسرع، وابنِ جمهور بيدفعلك", icon: "🎨", coursesCount: 7 },
  { title: "الذكاء الاصطناعي للمطورين", description: "ابنِ أسرع واشحن أكتر وابقَ متقدم دايمًا", icon: "⌨️", coursesCount: 6 },
];
