/**
 * "100 برومبت" — the lead magnet.
 *
 * Real, usable templates, not filler written to hit a round number. Every
 * one follows the same rule the AI Hub articles do: specific enough to copy,
 * paste, fill in the brackets, and use today — not a generic "write me a
 * post about X" a reader could have thought of themselves.
 */
export type PromptCategory = {
  key: string;
  title: string;
  titleEn: string;
  icon: string;
  prompts: string[];
  promptsEn: string[];
};

export const promptCategories: PromptCategory[] = [
  {
    key: "work",
    title: "الشغل اليومي",
    titleEn: "Daily Work & Productivity",
    icon: "💼",
    prompts: [
      "لخّصلي الاجتماع ده في ٥ نقط بس، وحدّد أي قرارات اتاخدت وأي مهام اتوزّعت على مين: [الصق محضر الاجتماع]",
      "حوّل الملاحظات دي لإيميل متابعة احترافي وقصير: [الصق الملاحظات]",
      "راجع الإيميل ده وقولي هل نبرته مناسبة للموقف ده: [الصق الإيميل] + [الموقف]",
      "اكتبلي رد مهذب على الإيميل ده بيرفض الطلب من غير ما يبان جامد: [الصق الإيميل]",
      "حوّل قايمة المهام دي لجدول بأولويات حسب الأهم والأعجل: [الصق القايمة]",
      "لخّصلي التقرير ده في فقرة واحدة لمدير مستعجل: [الصق التقرير]",
      "اكتبلي أجندة اجتماع لمدة ٣٠ دقيقة عن الموضوع ده: [الموضوع]",
      "راجع الرسالة دي وقولي هل فيها أي غموض ممكن يتفهم غلط: [الصق الرسالة]",
      "حوّل النقط دي لعرض تقديمي من ٥ شرائح بعناوين وملخص كل شريحة: [الصق النقط]",
      "اقترح ٣ طرق أرد بيها على السؤال الصعب ده من مديري: [السؤال]",
    ],
    promptsEn: [
      "Summarize this meeting into exactly 5 key takeaways, identifying all decisions made and action items assigned with their owners: [Paste meeting transcript]",
      "Convert these rough notes into a concise, professional follow-up email: [Paste notes]",
      "Review this email and tell me if the tone is appropriate for this specific situation: [Paste email] + [Situation]",
      "Draft a polite email response declining this request without sounding harsh or uncooperative: [Paste email]",
      "Transform this task list into an Eisenhower priority matrix based on urgency and importance: [Paste task list]",
      "Summarize this comprehensive report into a single concise paragraph for an executive with zero time: [Paste report]",
      "Create an efficient 30-minute meeting agenda for the following topic, including time allocations per section: [Topic]",
      "Review this message and highlight any ambiguity or phrases that could be misinterpreted: [Paste message]",
      "Convert these bullet points into a 5-slide presentation outline with slide titles and bulleted talking points: [Paste points]",
      "Suggest 3 constructive ways to answer this challenging question from my manager: [Question]",
    ],
  },
  {
    key: "content",
    title: "الكتابة والمحتوى",
    titleEn: "Writing & Content Creation",
    icon: "✍️",
    prompts: [
      "اكتبلي ٣ عناوين مختلفة لمنشور عن [الموضوع]، كل واحد بزاوية مختلفة (فضول، رقم، سؤال)",
      "حوّل الفقرة دي لنسخة أقصر بنص الطول من غير ما يضيع المعنى: [الصق الفقرة]",
      "اقترحلي ٥ أفكار محتوى عن [الموضوع] تناسب جمهور [وصف الجمهور]",
      "راجع النص ده وقولي أماكن التكرار أو الجمل الطويلة اللي محتاجة تتقصّر: [الصق النص]",
      "حوّل المقال ده لخيط تويتر/X من ٦ تغريدات: [الصق المقال]",
      "اكتبلي كابشن لبوست انستجرام عن [الموضوع] بنبرة [ودودة/احترافية/فكاهية]",
      "اديني ٣ نهايات مختلفة للمقال ده تخلّي القارئ يتفاعل: [الصق المقال]",
      "حوّل الكلام العامي ده لنص فصيح مناسب لمقال: [الصق النص]",
      "اقترحلي عنوان SEO ووصف ميتا للمقال ده بحد أقصى ١٥٥ حرف: [الصق المقال]",
      "راجع النص ده من ناحية الأخطاء الإملائية والنحوية بس، من غير ما تغيّر الأسلوب: [الصق النص]",
    ],
    promptsEn: [
      "Write 3 distinct headlines for a post about [Topic], each using a different angle (curiosity, data/numbers, contrarian question):",
      "Condense this paragraph to half its length while retaining 100% of the core message and impact: [Paste paragraph]",
      "Generate 5 high-converting content ideas about [Topic] tailored for [Audience description]:",
      "Audit this text and highlight repetitive words, passive phrasing, or run-on sentences that should be tightened: [Paste text]",
      "Repurpose this long-form article into an engaging 6-part Twitter/X thread with a strong hook: [Paste article]",
      "Write an engaging Instagram caption for [Topic] with a [friendly / professional / witty] tone, including call to action:",
      "Provide 3 compelling concluding paragraphs for this article that drive reader engagement and comments: [Paste article]",
      "Refine this casual draft into polished, publication-ready prose suitable for a professional journal: [Paste text]",
      "Suggest an SEO-optimized title tag and meta description under 155 characters for this article: [Paste article]",
      "Proofread this draft exclusively for grammatical, punctuation, and spelling errors without altering my voice: [Paste text]",
    ],
  },
  {
    key: "business",
    title: "المشروع والأعمال",
    titleEn: "Business & Entrepreneurship",
    icon: "📈",
    prompts: [
      "اسألني ٥ أسئلة تساعدني أوضّح فكرة المشروع ده أكتر: [وصف المشروع بسطرين]",
      "قيّم فكرة المنتج دي من ناحية: مين هيشتريه، وليه هيشتريه مني أنا مش من حد تاني: [وصف المنتج]",
      "اقترحلي ٣ طرق تسعير مختلفة للخدمة دي مع مميزات وعيوب كل طريقة: [وصف الخدمة]",
      "حلّل الشكوى دي من عميل وقولي هل هي مشكلة حقيقية في المنتج ولا حالة فردية: [الصق الشكوى]",
      "اكتبلي رد على عميل غاضب من تأخير في التسليم، يعتذر من غير ما يوعد بحاجة مش هينفّذها: [تفاصيل الموقف]",
      "قارن بين الخيارين دول لمورّد/شريك واقترح أسئلة أسألها قبل ما أقرر: [الخيار الأول] و[الخيار التاني]",
      "حوّل الأرقام دي لملخص فهمين لصاحب قرار مش متخصص في الأرقام: [الصق الأرقام]",
      "اقترحلي ٣ مخاطر ممكن أكون مش فاكرها في الخطة دي: [وصف الخطة]",
      "اكتبلي وصف منتج قصير يركّز على النتيجة اللي العميل هياخدها مش المواصفات: [تفاصيل المنتج]",
      "راجع عرض السعر ده وقولي هل في حاجة غير واضحة للعميل: [الصق العرض]",
    ],
    promptsEn: [
      "Ask me 5 diagnostic questions to help sharpen and validate this business idea: [2-sentence idea description]",
      "Evaluate this product value proposition: who will buy it, and why choose me over established competitors? [Product description]",
      "Propose 3 distinct pricing models for this service with pros, cons, and customer perception for each: [Service description]",
      "Analyze this customer complaint: is it an isolated edge case or a systemic product flaw? [Paste complaint]",
      "Draft a response to a frustrated customer about a shipping delay, offering sincere empathy without making unfeasible promises: [Situation]",
      "Compare these two vendor/partner options and suggest 5 critical due diligence questions before signing: [Option A] and [Option B]",
      "Translate these complex financial metrics into a clear executive summary for non-technical stakeholders: [Paste metrics]",
      "Identify 3 blind spots or strategic risks that I may have overlooked in this launch plan: [Plan summary]",
      "Write a persuasive, benefits-driven product description focused on transformation rather than technical features: [Product specs]",
      "Review this proposal quotation and identify any clauses or pricing structures that could confuse the client: [Paste proposal]",
    ],
  },
  {
    key: "learning",
    title: "التعلّم والمذاكرة",
    titleEn: "Learning & Study Mastery",
    icon: "🎓",
    prompts: [
      "اشرحلي [موضوع معقّد] زي ما هتشرحه لحد عمره ١٢ سنة",
      "اعملّي ٥ أسئلة اختبار نفسي عن الموضوع ده عشان أتأكد إني فاهمه: [الموضوع]",
      "لخّصلي الفصل ده في خريطة ذهنية نصية (عناوين وتحتها نقط): [الصق النص]",
      "قارن بين المفهومين دول بجدول بسيط: [المفهوم الأول] و[المفهوم التاني]",
      "اديني مثال عملي من الحياة اليومية يوضّح المفهوم ده: [المفهوم]",
      "راجع الإجابة دي وقولي فين الخطأ في تفكيري: [الصق إجابتك]",
      "اعملّي جدول مذاكرة لأسبوع لموضوع [الموضوع] مع وقت مقترح لكل جزء",
      "حوّل المعلومات دي لبطاقات مراجعة (سؤال وجواب): [الصق المعلومات]",
      "اشرحلي الفرق بين [مصطلح أول] و[مصطلح تاني] اللي بيتلخبطوا مع بعض",
      "اديني ٣ طرق مختلفة أتذكّر بيها المعلومة دي: [المعلومة]",
    ],
    promptsEn: [
      "Explain [Complex concept] as if you were explaining it to a curious 12-year-old using simple analogies:",
      "Generate 5 challenging conceptual self-quiz questions to test my deep understanding of: [Topic]",
      "Summarize this textbook chapter into a hierarchical text mind map with main concepts and sub-branches: [Paste chapter]",
      "Create a direct comparison table comparing [Concept A] and [Concept B] across key criteria:",
      "Provide a concrete real-world example from everyday life illustrating how [Concept] works in practice:",
      "Review my reasoning for this problem and pinpoint the exact logical fallacy or gap: [Paste my answer]",
      "Design a realistic 7-day study schedule for mastering [Topic] with suggested time blocks per milestone:",
      "Convert this study material into 10 active-recall flashcard pairs (Question and Answer format): [Paste notes]",
      "Explain the subtle distinctions between [Term A] and [Term B] that students frequently confuse:",
      "Suggest 3 evidence-based mnemonic techniques to easily memorize and retain this specific information: [Information]",
    ],
  },
  {
    key: "career",
    title: "الوظيفة والمقابلات",
    titleEn: "Career & Interview Prep",
    icon: "🧑‍💼",
    prompts: [
      "راجع السطر ده في الـCV وحوّله لصيغة فيها رقم أو نتيجة بدل وصف عام: [الصق السطر]",
      "اعملّي ٥ أسئلة متوقعة في مقابلة لوظيفة [المسمى الوظيفي] وامثلة إجابات",
      "حوّل الموقف ده لإجابة بطريقة STAR (الموقف، المهمة، الإجراء، النتيجة): [وصف الموقف]",
      "راجع خطاب التقديم ده وقولي هل بيوضّح ليه أنا المناسب للوظيفة: [الصق الخطاب]",
      "اقترحلي ٣ أسئلة أسألها في نهاية المقابلة تبيّن اهتمامي الحقيقي",
      "اعملّي جدول مقارنة بين عرضين وظيفة على أساس معايير غير الراتب بس: [تفاصيل العرضين]",
      "حوّل خبرتي دي لجملة قصيرة أقولها في مقابلة (elevator pitch): [وصف خبرتك]",
      "راجع الرد ده على سؤال 'ليه سبت شغلك اللي فات' وقولي هل فيه أي علامة سلبية: [الصق الرد]",
      "اقترحلي إزاي أفاوض على الراتب في الموقف ده من غير ما أخسر العرض: [تفاصيل الموقف]",
      "حوّل مهاراتي دي لنقط في بروفايل لينكدإن مقنعة: [قايمة المهارات]",
    ],
    promptsEn: [
      "Rewrite this resume bullet point into the XYZ format (Accomplished [X] as measured by [Y] by doing [Z]): [Paste bullet]",
      "Generate 5 rigorous interview questions likely asked for a [Job Title] role along with ideal response benchmarks:",
      "Structure this past project experience into a concise STAR-method interview response (Situation, Task, Action, Result): [Details]",
      "Critique this cover letter and assess whether it clearly demonstrates why I am uniquely qualified: [Paste letter]",
      "Suggest 3 insightful, reverse-interview questions to ask the hiring committee that demonstrate strategic thinking:",
      "Create a structured comparison matrix evaluating two job offers across compensation, culture, career runway, and commute: [Offer details]",
      "Craft a memorable 30-second elevator pitch summarizing my professional background and unique edge: [Experience summary]",
      "Review my proposed answer to 'Why did you leave your previous position?' and eliminate any unintended negative subtext: [Paste answer]",
      "Provide a strategic salary negotiation script for this specific counter-offer scenario: [Situation details]",
      "Transform this list of hard skills into engaging LinkedIn profile experience bullet points: [List of skills]",
    ],
  },
  {
    key: "marketing",
    title: "التسويق والإعلانات",
    titleEn: "Marketing & Advertising",
    icon: "📣",
    prompts: [
      "اقترحلي ٥ زوايا مختلفة أقدر أعلن بيها عن نفس المنتج ده: [وصف المنتج]",
      "اكتبلي نص إعلان قصير (حد أقصى ٤٠ كلمة) يركّز على مشكلة واحدة بيحلّها المنتج: [المنتج والمشكلة]",
      "راجع النص الإعلاني ده وقولي هل الـCTA واضح وقوي: [الصق النص]",
      "اقترحلي ٣ اعتراضات ممكن العميل يفكر فيها قبل ما يشتري، ورد على كل واحد: [المنتج]",
      "حوّل نتايج العميل دي لقصة نجاح قصيرة (قبل/بعد): [تفاصيل النتيجة]",
      "اعملّي كالندر محتوى لأسبوع لصفحة [نوع النشاط] بعناوين بس مش نص كامل",
      "اقترحلي هاشتاجات مناسبة لبوست عن [الموضوع] للسوق المصري تحديدًا",
      "راجع صفحة الهبوط دي وقولي أول حاجة تحسّنها في الهيرو: [وصف الصفحة أو الصقها]",
      "اقترحلي ٣ أفكار Hook لفيديو قصير عن [الموضوع]",
      "حوّل التقييمات دي من العملاء لجملة اقتباس قصيرة أستخدمها في التسويق: [الصق التقييمات]",
    ],
    promptsEn: [
      "Generate 5 distinct advertising angles targeting different pain points and desires for this product: [Product description]",
      "Write a punchy 40-word ad copy focusing on the single most painful frustration this product solves: [Product & pain point]",
      "Audit this ad copy draft and evaluate whether the call-to-action is clear, compelling, and friction-free: [Paste copy]",
      "Anticipate the top 3 purchasing objections a prospect might have and provide a persuasive rebuttal for each: [Product]",
      "Transform this customer testimonial into a high-converting case study snippet (Before, Challenge, Transformation, Result): [Details]",
      "Create a 7-day social media content theme calendar for a [Business type] focusing on engagement and authority:",
      "Suggest relevant, high-traction hashtags for a campaign about [Topic] specifically targeting the regional market:",
      "Audit this landing page hero section and recommend the top 2 tweaks to boost above-the-fold conversion: [Landing page copy]",
      "Identify 3 high-converting marketing hooks for a 30-second short-form video about [Topic]:",
      "Distill these customer reviews into 3 powerful pull-quote headlines for a landing page testimonials section: [Paste reviews]",
    ],
  },
  {
    key: "data",
    title: "البيانات والتحليل",
    titleEn: "Data & Analytical Thinking",
    icon: "📊",
    prompts: [
      "اشرحلي إيه اللي الأرقام دي بتقوله فعليًا بلغة بسيطة: [الصق الأرقام]",
      "اقترحلي ٣ رسوم بيانية مناسبة لعرض البيانات دي وليه: [وصف البيانات]",
      "دوّر على أي تناقض أو رقم غريب في الجدول ده: [الصق الجدول]",
      "حوّل التحليل ده لتوصية واحدة واضحة لصاحب القرار: [الصق التحليل]",
      "اقترحلي معادلة إكسل تعمل [الحاجة اللي عايز تعملها]",
      "اشرحلي الفرق بين المتوسط والوسيط في الحالة دي وأنهي واحد أنسب أستخدمه: [وصف البيانات]",
      "راجع الاستنتاج ده وقولي هل مبني على البيانات فعلًا ولا افتراض: [الصق الاستنتاج]",
      "اقترحلي ٣ أسئلة أسألها عن البيانات دي قبل ما أثق في النتيجة: [وصف البيانات]",
      "حوّل جدول البيانات ده لملخص من ٣ جمل: [الصق الجدول]",
      "اشرحلي إزاي أفسّر نسبة النمو دي — هل هي كويسة ولا لأ مقارنة بإيه: [الرقم والسياق]",
    ],
    promptsEn: [
      "Interpret what these numbers actually mean in plain English for a non-analyst stakeholder: [Paste data]",
      "Recommend the 3 most effective visualization charts for presenting this dataset and explain why: [Data description]",
      "Examine this data table and identify any anomalies, outliers, or inconsistent patterns: [Paste table]",
      "Distill this technical data analysis into a single clear, actionable business recommendation: [Paste analysis]",
      "Write an Excel / Google Sheets formula to accomplish the following calculation: [Desired calculation]",
      "Explain whether mean or median is more appropriate for this distribution and why: [Data description]",
      "Audit this business conclusion: is it firmly supported by the data, or is it an unsupported correlation/assumption? [Conclusion]",
      "Suggest 3 critical data hygiene and validation questions to ask before trusting this metric: [Metric context]",
      "Summarize the primary takeaways from this financial / operational dataset into 3 bullet points: [Paste table]",
      "Explain how to interpret this growth rate metric: is it statistically meaningful in this context? [Metric and context]",
    ],
  },
  {
    key: "problem-solving",
    title: "حل المشاكل والقرارات",
    titleEn: "Problem Solving & Decision Making",
    icon: "🧩",
    prompts: [
      "اسألني أسئلة توضّحلي المشكلة دي أكتر قبل ما نفكر في حل: [وصف المشكلة]",
      "اقترحلي ٣ حلول مختلفة للمشكلة دي، من الأبسط للأصعب: [المشكلة]",
      "قولي إيه أسوأ سيناريو ممكن يحصل لو اخترت الخيار ده، وإزاي أستعد له: [الخيار]",
      "قارن بين الخيارين دول على أساس التكلفة، الوقت، والمخاطرة: [الخيار الأول] و[الخيار التاني]",
      "اقترحلي ٣ أسئلة أسألها لنفسي قبل ما آخد القرار ده: [القرار]",
      "حلّل الموقف ده وقولي إيه اللي فعليًا تحت سيطرتي وإيه مش تحت سيطرتي: [الموقف]",
      "اقترحلي طريقة أقسّم بيها المشكلة الكبيرة دي لخطوات أصغر: [المشكلة]",
      "قولي هل القرار ده بيتاخد تحت ضغط وقت حقيقي ولا أنا بس مستعجل: [الموقف]",
      "اعملّي جدول إيجابيات وسلبيات للخيار ده: [الخيار]",
      "اقترحلي حل وسط بين الرأيين المتعارضين دول: [الرأي الأول] و[الرأي التاني]",
    ],
    promptsEn: [
      "Ask me diagnostic Socratic questions to unpack the root cause of this problem before jumping into solutions: [Problem description]",
      "Propose 3 distinct solutions to this challenge ranging from easiest to implement to highest potential upside: [Problem]",
      "Perform a premortem analysis: what is the worst-case scenario if we choose this option, and how do we mitigate it? [Option]",
      "Compare these two strategic options across cost, implementation timeline, and operational risk: [Option A] and [Option B]",
      "Suggest 3 fundamental questions I should ask myself before committing to this irreversible decision: [Decision]",
      "Analyze this stressful situation and categorize factors into what is within my control vs outside my control: [Situation]",
      "Deconstruct this overwhelming, ambiguous project into a sequence of bite-sized, manageable milestones: [Problem]",
      "Evaluate whether this decision is being forced by artificial urgency or real business time constraints: [Situation]",
      "Create a balanced, objective pros-and-cons matrix weighted by long-term impact for this choice: [Option]",
      "Formulate an elegant compromise between these two conflicting stakeholder perspectives: [Perspective A] and [Perspective B]",
    ],
  },
  {
    key: "communication",
    title: "التواصل والعلاقات",
    titleEn: "Communication & Relationships",
    icon: "💬",
    prompts: [
      "راجع الرسالة دي قبل ما أبعتها وقولي هل فيها أي نبرة ممكن تتفهم غلط: [الصق الرسالة]",
      "ساعدني أصيغ اعتذار حقيقي على الموقف ده من غير مبالغة: [الموقف]",
      "اقترحلي إزاي أبدأ محادثة صعبة عن [الموضوع] مع [الشخص]",
      "حوّل الشكوى دي لطلب واضح بدل ما تبقى مجرد تذمّر: [الصق الشكوى]",
      "اقترحلي رد لطيف بس واضح أرفض بيه الطلب ده من غير شعور بالذنب: [الطلب]",
      "ساعدني أعبّر عن رأيي المختلف في الاجتماع من غير ما أبان معارض بشكل حاد: [الرأي]",
      "اقترحلي ٣ أسئلة أفتح بيها محادثة تعارف حقيقية مش سطحية",
      "راجع الرسالة دي وقولي هل هي أطول من اللازم للموقف ده: [الصق الرسالة]",
      "ساعدني أشكر حد على مجهوده بطريقة مش عامة أو مكررة: [تفاصيل المجهود]",
      "اقترحلي إزاي أوصّل رأي ناقد لحد من غير ما أجرح مشاعره: [الموقف]",
    ],
    promptsEn: [
      "Review this sensitive message before I send it and identify any unintentional aggressive or defensive phrasing: [Paste draft]",
      "Help me draft a genuine, accountable apology for this misstep without over-explaining or sounding defensive: [Situation]",
      "Provide a framework on how to initiate a difficult conversation regarding [Topic] with [Person]:",
      "Rephrase this frustrated grievance into a constructive, outcome-oriented request: [Paste grievance]",
      "Draft a warm, polite, but firm boundary to decline this request without feeling guilty: [Request description]",
      "Help me articulate a contrarian viewpoint during an upcoming executive meeting without appearing combative: [Perspective]",
      "Suggest 3 natural, non-generic open-ended questions to start an authentic professional networking conversation:",
      "Assess this message draft: is it too verbose for the channel, and how can I cut 40% of the words? [Paste message]",
      "Write a sincere, personalized note of gratitude acknowledging someone's specific contributions: [Details of contribution]",
      "Suggest an empathetic way to deliver constructive critique to a peer without damaging morale: [Situation]",
    ],
  },
  {
    key: "personal",
    title: "التطوير الشخصي",
    titleEn: "Personal Growth & Habits",
    icon: "🌱",
    prompts: [
      "اسألني أسئلة تساعدني أوضّح هدفي الحقيقي من [الحاجة اللي عايز تحققها]",
      "حوّل الهدف الكبير ده لخطوات أسبوعية واقعية: [الهدف]",
      "اقترحلي عادة صغيرة واحدة تساعدني أوصل للهدف ده بدل خطة كبيرة معقّدة: [الهدف]",
      "راجع يومي وقولي أين وقتي بيضيع فعليًا: [وصف يومك]",
      "اقترحلي ٣ أسئلة أسألها لنفسي كل أسبوع أراجع بيها تقدّمي",
      "ساعدني أفهم ليه بأأجّل المهمة دي بالذات: [المهمة]",
      "اقترحلي طريقة أحتفل بيها بإنجاز صغير من غير ما أستهين بيه",
      "حوّل الشكوى دي من نفسي لخطة عملية بدل جلد ذات: [الشكوى]",
      "اقترحلي سؤال أسأله لنفسي في نهاية كل يوم يساعدني أتعلّم من اليوم ده",
      "ساعدني أفرّق بين الكسل والإرهاق الحقيقي في الموقف ده: [وصف الموقف]",
    ],
    promptsEn: [
      "Ask me 5 targeted questions to clarify my true underlying intrinsic motivation behind this goal: [Goal description]",
      "Break down this ambitious annual goal into realistic, bite-sized weekly habits: [Goal]",
      "Suggest one tiny 'atomic' 2-minute daily habit that creates momentum toward this objective: [Goal]",
      "Audit my daily schedule and highlight where hidden time-leaks and friction points are occurring: [Daily schedule description]",
      "Provide 3 thoughtful weekly self-reflection prompts to evaluate my personal and professional trajectory:",
      "Help me identify the underlying psychological trigger behind why I keep procrastinating on this specific task: [Task]",
      "Recommend a meaningful, non-monetary ritual to acknowledge and celebrate small incremental wins:",
      "Reframe this harsh self-criticism into an actionable, constructive growth plan: [Self-critique statement]",
      "Suggest a 2-minute evening journaling question that maximizes learning and closure from each day:",
      "Help me discern whether what I'm feeling right now is resistance/laziness or genuine cognitive exhaustion: [Context]",
    ],
  },
];

export const totalPromptCount = promptCategories.reduce((s, c) => s + c.prompts.length, 0);
