import type { Track100 } from "./tracks100";

export const TRACKS_51_100: Track100[] = [
  // --- PILLAR 6: UI/UX & CREATIVE MEDIA (51-60) ---
  {
    id: 51,
    slug: "ui-ux-design-figma",
    order: 51,
    pillarId: 6,
    pillarNameAr: "التصميم والميديا",
    pillarNameEn: "Design & Media",
    titleAr: "أساسيات وتصميم تجربة المستخدم (UI/UX with Figma)",
    titleEn: "UI/UX Design Fundamentals with Figma",
    descriptionAr: "تعلم مبادئ التصميم البصري، تخطيط الواجهات، وبناء نماذج تفاعلية كاملة للمواقع وتطبيقات الموبايل.",
    descriptionEn: "Master visual hierarchy, component systems, and interactive clickable prototypes in Figma.",
    levelAr: "مبتدئ",
    levelEn: "Beginner",
    totalLessons: 26,
    durationHours: 4,
    totalXp: 2100,
    icon: "🎨",
    accentFrom: "#a855f7",
    accentTo: "#7e22ce",
    outcomesAr: ["إتقان Auto-Layout والمكونات التفاعلية في Figma", "تصميم شبكات متناسقة وأنظمة ألوان وطباعة مريحة للعين", "بناء نماذج أولية قابلة للاختبار مع مستخدمين حقيقيين"],
    outcomesEn: ["Master Auto-Layout, variants, and component properties", "Establish harmonious color palettes and typography scales", "Build testable interactive prototypes for user feedback"],
    realityAr: "التصميم الجيد ليس مجرد مظهر جميل، بل حل واضح وسهل لمشكلة المستخدم.",
    realityEn: "UI/UX design is not decoration; it is functional clarity that solves human friction.",
    badgeTitleAr: "مصمم واجهات معتمد",
    badgeTitleEn: "UI/UX Designer",
  },
  {
    id: 52,
    slug: "user-research-wireframing",
    order: 52,
    pillarId: 6,
    pillarNameAr: "التصميم والميديا",
    pillarNameEn: "Design & Media",
    titleAr: "أبحاث المستخدم ورسم الهياكل السلكية (Wireframing)",
    titleEn: "User Research & Rapid Wireframing",
    descriptionAr: "كيف تجري مقابلات المستخدمين، تكتشف نقاط الألم الحقيقية، وترسم رحلة العميل قبل البدء في الألوان.",
    descriptionEn: "Conduct user interviews, map customer journeys, and sketch rapid low-fidelity wireframes.",
    levelAr: "متوسط",
    levelEn: "Intermediate",
    totalLessons: 20,
    durationHours: 3,
    totalXp: 1800,
    icon: "📋",
    accentFrom: "#8b5cf6",
    accentTo: "#6d28d9",
    outcomesAr: ["إجراء اختبارات قابلية الاستخدام (Usability Testing)", "رسم مخططات التدفق (User Flow Diagrams)", "اكتشاف العوائق الخفية التي تجعل المستخدمين يغادرون التطبيق"],
    outcomesEn: ["Facilitate unmoderated and live usability tests", "Map intuitive user flows and information architectures", "Pinpoint hidden stumbling blocks causing user churn"],
    realityAr: "ساعة واحدة من اختبار المستخدمين توفر عليك أسابيع من إعادة البرمجة والتصميم الخاطئ.",
    realityEn: "One hour of user testing saves weeks of building the wrong features.",
    badgeTitleAr: "باحث تجربة مستخدم",
    badgeTitleEn: "UX Researcher",
  },
  {
    id: 53,
    slug: "scalable-design-systems",
    order: 53,
    pillarId: 6,
    pillarNameAr: "التصميم والميديا",
    pillarNameEn: "Design & Media",
    titleAr: "أنظمة التصميم الاحترافية للمنتجات (Design Systems)",
    titleEn: "Scalable Product Design Systems",
    descriptionAr: "بناء مكتبات تصميم شاملة للمؤسسات تضمن تناسق الأزرار والخطوط وسرعة تسليم المطورين 10x.",
    descriptionEn: "Construct enterprise design systems with design tokens, component variants, and dev handoff specs.",
    levelAr: "متقدم",
    levelEn: "Advanced",
    totalLessons: 22,
    durationHours: 3.5,
    totalXp: 2200,
    icon: "🏛️",
    accentFrom: "#6b21a8",
    accentTo: "#4c1d95",
    outcomesAr: ["بناء وإدارة الـ Design Tokens وتحديثها تلقائياً", "توثيق المكونات وتسهيل التسليم للمبرمجين (Handoff)", "الحفاظ على هوية متطابقة عبر عشرات الصفحات والتطبيقات"],
    outcomesEn: ["Architect design tokens synchronized with frontend code", "Document components for seamless developer handoff", "Maintain visual brand parity across web, iOS, and Android"],
    realityAr: "أنظمة التصميم هي استثمار في السرعة المؤسسية؛ كل ساعة تبذلها فيها توفر عشرات الساعات لاحقاً.",
    realityEn: "A design system is an investment in velocity; it prevents perpetual reinvention.",
    badgeTitleAr: "معماري أنظمة التصميم",
    badgeTitleEn: "Design Systems Architect",
  },
  {
    id: 54,
    slug: "brand-identity-visual-storytelling",
    order: 54,
    pillarId: 6,
    pillarNameAr: "التصميم والميديا",
    pillarNameEn: "Design & Media",
    titleAr: "تصميم الهوية البصرية وسرد قصة العلامة التجارية",
    titleEn: "Brand Identity & Visual Storytelling",
    descriptionAr: "ابتكار هويات بصرية لا تنسى: الشعار، الألوان، الخطوط، ودليل إرشادات الهوية للشركات.",
    descriptionEn: "Create memorable corporate visual identities: logos, typography guidelines, and brand books.",
    levelAr: "مبتدئ",
    levelEn: "Beginner",
    totalLessons: 22,
    durationHours: 3.5,
    totalXp: 1900,
    icon: "💎",
    accentFrom: "#d946ef",
    accentTo: "#a21caf",
    outcomesAr: ["تصميم شعارات ذات معنى عميق وبسيطة التذكر", "اختيار سيكولوجيا الألوان التي تزرع الثقة في العميل", "إنتاج كتيب إرشادات الهوية (Brand Guidelines Book) المتكامل"],
    outcomesEn: ["Design timeless, memorable vector logos", "Apply color psychology that engenders instant customer trust", "Compile comprehensive brand guideline manuals"],
    realityAr: "الهوية ليست مجرد لوجو؛ هي الانطباع والشعور الذي يتركه عملك في أذهان الناس.",
    realityEn: "Brand identity is far more than a logo; it is the emotional imprint your business leaves behind.",
    badgeTitleAr: "مصمم هويات بصرية",
    badgeTitleEn: "Brand Identity Designer",
  },
  {
    id: 55,
    slug: "short-form-video-editing",
    order: 55,
    pillarId: 6,
    pillarNameAr: "التصميم والميديا",
    pillarNameEn: "Design & Media",
    titleAr: "مونتاج الفيديو القصير لصناع المحتوى (Reels & Shorts)",
    titleEn: "Short-Form Video Editing (CapCut & Premiere)",
    descriptionAr: "مونتاج الفيديوهات الرائجة: القطعات السريعة، النصوص المتحركة، المؤثرات الصوتية، والمحتوى الجذاب.",
    descriptionEn: "Edit viral short-form videos with dynamic pacing, kinetic typography, b-roll, and SFX.",
    levelAr: "مبتدئ",
    levelEn: "Beginner",
    totalLessons: 24,
    durationHours: 3.5,
    totalXp: 1800,
    icon: "✂️",
    accentFrom: "#f43f5e",
    accentTo: "#be123c",
    outcomesAr: ["إتقان المونتاج الإيقاعي الذي يحافظ على تركيز المشاهد", "إضافة نصوص متحركة ورموز تعبيرية جذابة (Captions)", "دمج المؤثرات الصوتية والموسيقى في اللحظة المناسبة تماماً"],
    outcomesEn: ["Master retention-based fast-paced visual editing", "Animate eye-catching kinetic subtitles and emojis", "Layer SFX sound effects to punctuate every key insight"],
    realityAr: "المشاهد يحكم على الفيديو في أول 3 ثوانٍ؛ المونتاج الاحترافي هو ما يمنعه من التمرير للأعلى.",
    realityEn: "Viewers decide within 3 seconds; magnetic editing is what prevents the instant swipe.",
    badgeTitleAr: "محرر فيديو قصير",
    badgeTitleEn: "Short-Form Video Editor",
  },
  {
    id: 56,
    slug: "motion-graphics-after-effects",
    order: 56,
    pillarId: 6,
    pillarNameAr: "التصميم والميديا",
    pillarNameEn: "Design & Media",
    titleAr: "تصميم الموشن جرافيكس للإعلانات (After Effects)",
    titleEn: "Motion Graphics with After Effects",
    descriptionAr: "تحريك العناصر والرسومات وتصميم إعلانات موشن جرافيكس حركية مذهلة تزيد من مبيعات المنتجات.",
    descriptionEn: "Bring illustrations to life with After Effects keyframe animations, typography, and visual dynamics.",
    levelAr: "متوسط",
    levelEn: "Intermediate",
    totalLessons: 26,
    durationHours: 4.5,
    totalXp: 2300,
    icon: "🎞️",
    accentFrom: "#9333ea",
    accentTo: "#6b21a8",
    outcomesAr: ["فهم قوانين الحركة الاثني عشر (12 Principles of Animation)", "تحريك النصوص والشعارات بانسيابية عالية", "تصدير الفيديوهات بأعلى جودة وأخف حجم ممكن"],
    outcomesEn: ["Apply Disney's 12 principles of fluid animation", "Animate logos and commercial typography gracefully", "Export optimized lightweight video assets for ad networks"],
    realityAr: "الموشن جرافيكس يحتاج صبراً في ضبط منحنيات السرعة (Speed Graphs) لتكون الحركة طبيعية.",
    realityEn: "Smooth motion design requires patient mastery of Bezier speed graphs.",
    badgeTitleAr: "مصمم موشن جرافيكس",
    badgeTitleEn: "Motion Designer",
  },
  {
    id: 57,
    slug: "3d-design-blender-basics",
    order: 57,
    pillarId: 6,
    pillarNameAr: "التصميم والميديا",
    pillarNameEn: "Design & Media",
    titleAr: "التصميم ثلاثي الأبعاد للمبتدئين (Blender 3D)",
    titleEn: "3D Product Modeling with Blender",
    descriptionAr: "تصميم مجسمات ورندرات منتجات ثلاثية الأبعاد جذابة لإعلانات التجارة الإلكترونية والمواقع.",
    descriptionEn: "Model, texture, light, and render commercial 3D product visuals using free open-source Blender.",
    levelAr: "متوسط",
    levelEn: "Intermediate",
    totalLessons: 24,
    durationHours: 4,
    totalXp: 2200,
    icon: "🧊",
    accentFrom: "#ea580c",
    accentTo: "#c2410c",
    outcomesAr: ["النمذجة ثلاثية الأبعاد الأساسية للمنتجات والعلب", "توزيع الإضاءة الاستوديو والخامات الواقعية (PBR)", "رندر صور ثابتة ومقاطع دوران 360 درجة"],
    outcomesEn: ["Model commercial product packaging and bottles", "Setup photorealistic studio lighting and PBR materials", "Render high-res hero images and 360 turntable loops"],
    realityAr: "الـ 3D يمنحك حرية خيالية لا تملكها الكاميرا، لكنه يحتاج فهماً جيداً للإضاءة والظلال.",
    realityEn: "3D offers boundless visual control, but depends heavily on mastering lighting physics.",
    badgeTitleAr: "فنان ثلاثي الأبعاد",
    badgeTitleEn: "3D Visualizer",
  },
  {
    id: 58,
    slug: "thumbnail-ad-creative-design",
    order: 58,
    pillarId: 6,
    pillarNameAr: "التصميم والميديا",
    pillarNameEn: "Design & Media",
    titleAr: "تصميم الصور المصغرة والبوسترات الإعلانية (Thumbnails)",
    titleEn: "Clickable Thumbnail & Ad Creative Design",
    descriptionAr: "سيكولوجيا تصميم الصور المصغرة لليوتيوب وبوسترات الإعلانات التي تضاعف معدل النقر (CTR).",
    descriptionEn: "Master the visual psychology behind YouTube thumbnails and ad creatives that demand clicks.",
    levelAr: "مبتدئ",
    levelEn: "Beginner",
    totalLessons: 20,
    durationHours: 3,
    totalXp: 1700,
    icon: "🖼️",
    accentFrom: "#e11d48",
    accentTo: "#be123c",
    outcomesAr: ["صناعة تباين لوني قوي يظهر بوضوح على شاشات الموبايل", "اختيار تعابير الوجوه والكلمات الأربع الأهم في البوستر", "تطبيق اختبارات A/B على الصور المصغرة لرفع المشاهدات"],
    outcomesEn: ["Build high-contrast visual hierarchies optimized for tiny mobile screens", "Select emotion-triggering expressions and punchy 3-word titles", "Execute thumbnail A/B tests to double video views"],
    realityAr: "الفيديو العظيم الذي لا يملك صورة مصغرة جذابة هو فيديو لن يشاهده أحد أبداً.",
    realityEn: "The greatest video with a boring thumbnail is a video nobody will ever watch.",
    badgeTitleAr: "أخصائي صور مصغرة",
    badgeTitleEn: "Thumbnail Specialist",
  },
  {
    id: 59,
    slug: "audio-podcasting-sound-design",
    order: 59,
    pillarId: 6,
    pillarNameAr: "التصميم والميديا",
    pillarNameEn: "Design & Media",
    titleAr: "هندسة الصوت والبودكاست وصناعة المؤثرات",
    titleEn: "Audio Engineering & Podcast Sound Design",
    descriptionAr: "تسجيل، تنظيف، وهندسة الصوت ليخرج نقيّاً ودافئاً مثل استوديوهات الراديو العالمية دون ضوضاء.",
    descriptionEn: "Record, clean, and master pristine podcast audio and vocal tracks with zero room echo or hiss.",
    levelAr: "مبتدئ",
    levelEn: "Beginner",
    totalLessons: 20,
    durationHours: 3,
    totalXp: 1700,
    icon: "🎙️",
    accentFrom: "#0284c7",
    accentTo: "#0369a1",
    outcomesAr: ["إزالة الضوضاء والصدى بنقرة واحدة باستخدام الـ AI والمعالجة", "ضبط مستويات الصوت (LUFS) لتتوافق مع Spotify و YouTube", "إضافة المؤثرات الصوتية والموسيقى الخلفية دون تغطية على الكلام"],
    outcomesEn: ["Eliminate background noise and room reverb with modern processing", "Normalize audio to international streaming standards (-14 LUFS)", "Balance background beds and stingers without overpowering dialogue"],
    realityAr: "المشاهد قد يتحمل جودة فيديو متوسطة، لكنه يغلق الفيديو فوراً إذا كان الصوت سيئاً أو مزعجاً.",
    realityEn: "Viewers tolerate mediocre video, but abandon poor, crackly audio within 5 seconds.",
    badgeTitleAr: "مهندس صوت وبودكاست",
    badgeTitleEn: "Podcast Audio Engineer",
  },
  {
    id: 60,
    slug: "creative-direction-pitching",
    order: 60,
    pillarId: 6,
    pillarNameAr: "التصميم والميديا",
    pillarNameEn: "Design & Media",
    titleAr: "التوجيه الفني والإنتاج الإبداعي للوكالات (Creative Direction)",
    titleEn: "Creative Direction & Campaign Pitching",
    descriptionAr: "قيادة الفرق الإبداعية، تحويل أفكار الحملات إلى Moodboards، وعرض الأفكار على كبار العملاء.",
    descriptionEn: "Lead creative teams, translate client briefs into moodboards, and pitch winning campaign visions.",
    levelAr: "متقدم",
    levelEn: "Advanced",
    totalLessons: 22,
    durationHours: 3.5,
    totalXp: 2200,
    icon: "🎬",
    accentFrom: "#0f766e",
    accentTo: "#115e59",
    outcomesAr: ["صياغة الرؤية الإبداعية للحملات الإعلانية المتكاملة", "إدارة المصممين والمحررين لضمان وحدة الأسلوب البصري", "تقديم عروض إبداعية مقنعة تفوز بالمناقصات الكبرى"],
    outcomesEn: ["Formulate unifying creative visions for multi-channel campaigns", "Direct designers, copywriters, and video teams cohesively", "Deliver persuasive creative pitch presentations that win accounts"],
    realityAr: "المدير الإبداعي لا ينفذ كل شيء بنفسه، بل يمتلك الرؤية ويوجه الآخرين لتحقيقها بأعلى جودة.",
    realityEn: "A Creative Director doesn't push every pixel; they protect the vision and elevate the team.",
    badgeTitleAr: "مدير إبداعي معتمد",
    badgeTitleEn: "Creative Director",
  },

  // --- PILLAR 7: ENTREPRENEURSHIP & STARTUPS (61-70) ---
  {
    id: 61,
    slug: "idea-validation-product-market-fit",
    order: 61,
    pillarId: 7,
    pillarNameAr: "ريادة الأعمال",
    pillarNameEn: "Entrepreneurship",
    titleAr: "توليد واختبار الأفكار وصلاحية السوق (Validation)",
    titleEn: "Startup Idea Validation & PMF",
    descriptionAr: "كيف تتأكد أن هناك عملاء مستعدين لدفع أموال حقيقية مقابل فكرتك قبل أن تستثمر جنيهاً واحداً في بنائها.",
    descriptionEn: "Validate customer demand and willingness to pay before writing code or spending capital.",
    levelAr: "مبتدئ",
    levelEn: "Beginner",
    totalLessons: 22,
    durationHours: 3.5,
    totalXp: 1900,
    icon: "💡",
    accentFrom: "#10b981",
    accentTo: "#059669",
    outcomesAr: ["تطبيق منهجية The Mom Test في استجواب العملاء بدون مجاملة", "بناء صفحات هبوط لاختبار الطلب المسبق (Smoke Tests)", "تحديد مؤشرات الملاءمة بين المنتج والسوق (Product-Market Fit)"],
    outcomesEn: ["Interview prospects without false validation using The Mom Test", "Launch smoke-test landing pages collecting real pre-orders", "Measure leading indicators of genuine Product-Market Fit"],
    realityAr: "السبب الأول لفشل الشركات الناشئة هو بناء منتج لا يريده أحد حقاً.",
    realityEn: "The #1 cause of startup failure is building something nobody actually wants or pays for.",
    badgeTitleAr: "مختبر أفكار ريادية",
    badgeTitleEn: "Venture Validator",
  },
  {
    id: 62,
    slug: "business-model-canvas-monetization",
    order: 62,
    pillarId: 7,
    pillarNameAr: "ريادة الأعمال",
    pillarNameEn: "Entrepreneurship",
    titleAr: "نموذج العمل التجاري وهندسة الإيرادات (Monetization)",
    titleEn: "Business Model Canvas & Monetization",
    descriptionAr: "رسم نموذج العمل التجاري وتحديد تدفقات الإيرادات: الاشتراكات، العمولات، الخدمات، والمنتجات الرقمية.",
    descriptionEn: "Map out viable business models: recurring SaaS subscriptions, transactional fees, and digital assets.",
    levelAr: "متوسط",
    levelEn: "Intermediate",
    totalLessons: 20,
    durationHours: 3,
    totalXp: 1800,
    icon: "📊",
    accentFrom: "#0284c7",
    accentTo: "#0369a1",
    outcomesAr: ["تعبئة مخطط نموذج العمل التجاري (Business Model Canvas)", "اختيار استراتيجية التسعير الأنسب لنموذج مشروعك", "تحديد مصادر الإيرادات المتكررة والمستدامة"],
    outcomesEn: ["Complete an actionable, iterated Business Model Canvas", "Align pricing structures to match unit economic realities", "Build recurring recurring revenue streams (ARR / MRR)"],
    realityAr: "فكرة رائعة بدون نموذج عمل واضح ومربح هي مجرد هواية مكلفة وليست شركة.",
    realityEn: "A brilliant idea without a profitable monetization engine is merely an expensive hobby.",
    badgeTitleAr: "مصمم نماذج أعمال",
    badgeTitleEn: "Business Model Architect",
  },
  {
    id: 63,
    slug: "building-launching-mvp",
    order: 63,
    pillarId: 7,
    pillarNameAr: "ريادة الأعمال",
    pillarNameEn: "Entrepreneurship",
    titleAr: "بناء وإطلاق نموذج المنتج الأولي (MVP in 14 Days)",
    titleEn: "Building & Launching an MVP in 14 Days",
    descriptionAr: "كيف تختصر شهور التطوير وتطلق منتجاً أولياً بسيطاً يعمل ويحل المشكلة الأساسية خلال أسبوعين فقط.",
    descriptionEn: "Strip away feature bloat and ship a functional Minimum Viable Product in under two weeks.",
    levelAr: "مبتدئ",
    levelEn: "Beginner",
    totalLessons: 22,
    durationHours: 3.5,
    totalXp: 2000,
    icon: "🚀",
    accentFrom: "#059669",
    accentTo: "#047857",
    outcomesAr: ["تحديد الميزة الجوهرية الوحيدة وتجاهل كل ما عداها في البداية", "إطلاق المنتج على Product Hunt ومجموعات العملاء المستهدفين", "جمع ردود أفعال المستخدمين الأوائل والتطوير السريع"],
    outcomesEn: ["Isolate the single core feature that delivers value", "Execute launch day playbooks on Product Hunt and community hubs", "Establish rapid feedback loops to iterate based on actual usage"],
    realityAr: "إذا لم تكن تشعر ببعض الإحراج من نسختك الأولى، فأنت قد تأخرت كثيراً في الإطلاق.",
    realityEn: "If you are not somewhat embarrassed by your first release, you launched too late.",
    badgeTitleAr: "مطلق منتجات سريعة",
    badgeTitleEn: "MVP Launcher",
  },
  {
    id: 64,
    slug: "zero-budget-traction-growth",
    order: 64,
    pillarId: 7,
    pillarNameAr: "ريادة الأعمال",
    pillarNameEn: "Entrepreneurship",
    titleAr: "استراتيجيات جذب أول 1000 عميل (Zero-Budget Traction)",
    titleEn: "Acquiring First 1,000 Customers",
    descriptionAr: "أساليب غير تقليدية لجلب المستخدمين الأوائل بالاتصال المباشر، المجتمعات، والشراكات بدون إعلانات مدفوعة.",
    descriptionEn: "Unconventional zero-dollar acquisition tactics: direct outreach, community seeding, and viral loops.",
    levelAr: "متوسط",
    levelEn: "Intermediate",
    totalLessons: 24,
    durationHours: 3.5,
    totalXp: 2100,
    icon: "🧲",
    accentFrom: "#d97706",
    accentTo: "#b45309",
    outcomesAr: ["القيام بأشياء لا تتوسع يدوياً في البداية (Do Things That Don't Scale)", "استقطاب العملاء من مجموعات فيسبوك ولينكد إن المستهدفة", "بناء حلقات إحالة وتوصية ذاتية (Viral Referral Loops)"],
    outcomesEn: ["Execute high-touch manual onboarding (Do things that don't scale)", "Infiltrate active online communities without being spammy", "Build built-in referral incentives encouraging viral shares"],
    realityAr: "في البداية، وظيفتك هي إقناع العملاء واحداً تلو الآخر حتى تشتعل الشرارة الأولى.",
    realityEn: "Early traction is won hand-to-hand, customer by customer, through relentless hustle.",
    badgeTitleAr: "خبير جذب العملاء الأوائل",
    badgeTitleEn: "Early Traction Specialist",
  },
  {
    id: 65,
    slug: "b2b-sales-pipeline-crm",
    order: 65,
    pillarId: 7,
    pillarNameAr: "ريادة الأعمال",
    pillarNameEn: "Entrepreneurship",
    titleAr: "مبيعات الشركات وإدارة خط الصفقات (B2B Sales & CRM)",
    titleEn: "B2B Sales Pipeline & CRM Mastery",
    descriptionAr: "كيف تبيع منتجك أو خدمتك للشركات الكبرى، وتدير مراحل التفاوض والعقود من الاتصال الأول حتى التوقيع.",
    descriptionEn: "Master enterprise enterprise deal cycles: cold outreach, discovery calls, objection handling, and closing.",
    levelAr: "متوسط",
    levelEn: "Intermediate",
    totalLessons: 22,
    durationHours: 3.5,
    totalXp: 2000,
    icon: "🤝",
    accentFrom: "#2563eb",
    accentTo: "#1d4ed8",
    outcomesAr: ["إجراء مكالمات استكشافية (Discovery Calls) تفهم ميزانية العميل", "التعامل مع اعتراضات الأسعار وتفضيل المنافسين", "إدارة ومتابعة خط الصفقات في الـ CRM دون نسيان أي عميل"],
    outcomesEn: ["Conduct structured discovery calls qualifying budget and decision-makers", "Handle common procurement objections and competitor comparisons", "Manage clean CRM pipelines ensuring no warm lead goes cold"],
    realityAr: "مبيعات B2B لا تعتمد على الضغط، بل على بناء علاقة ثقة ومساعدة العميل في إثبات الجدوى لمديره.",
    realityEn: "B2B sales is about helping your internal champion justify the purchase to their board.",
    badgeTitleAr: "محترف مبيعات الشركات",
    badgeTitleEn: "B2B Sales Specialist",
  },
  {
    id: 66,
    slug: "pitch-decks-fundraising-basics",
    order: 66,
    pillarId: 7,
    pillarNameAr: "ريادة الأعمال",
    pillarNameEn: "Entrepreneurship",
    titleAr: "إعداد عروض الاستثمار وجولات التمويل (Pitch Decks)",
    titleEn: "Pitch Decks & Venture Capital Basics",
    descriptionAr: "كيف تصمم عرضاً تقديمياً من 10 شرائح يقنع المستثمرين الملائكيين وصناديق رأس المال الجريء بتمويل مشروعك.",
    descriptionEn: "Structure a 10-slide pitch deck that captivates angel investors and VC partners to fund your startup.",
    levelAr: "متقدم",
    levelEn: "Advanced",
    totalLessons: 20,
    durationHours: 3,
    totalXp: 2100,
    icon: "💼",
    accentFrom: "#0f766e",
    accentTo: "#115e59",
    outcomesAr: ["صياغة الشرائح العشر الذهبية (المشكلة، الحل، السوق، الفريق)", "فهم شروط الاستثمار (SAFE notes & Term Sheets)", "الإجابة بثقة على أسئلة المستثمرين الصعبة والمفاجئة"],
    outcomesEn: ["Design the definitive 10-slide deck (Problem, Solution, TAM, Team)", "Decode valuation fundamentals and Term Sheet clauses", "Answer investor due-diligence interrogations with numbers-backed poise"],
    realityAr: "المستثمر يستثمر في الفريق وقدرته على التنفيذ السريع أكثر من استثماره في مجرد فكرة على ورق.",
    realityEn: "Investors back relentless execution velocity and team grit far more than initial ideas.",
    badgeTitleAr: "جاهز للاستثمار",
    badgeTitleEn: "Fundraising Ready",
  },
  {
    id: 67,
    slug: "unit-economics-startup-finance",
    order: 67,
    pillarId: 7,
    pillarNameAr: "ريادة الأعمال",
    pillarNameEn: "Entrepreneurship",
    titleAr: "الإدارة المالية الذكية للشركات الناشئة (Unit Economics)",
    titleEn: "Unit Economics & Startup Finance",
    descriptionAr: "حساب معدل حرق السيولة (Burn Rate)، والمدة المتبقية للبقاء (Runway)، وهندسة هامش الربح لكل عملية بيع.",
    descriptionEn: "Master cash burn rates, survival runway, gross profit contributions, and scalable unit economics.",
    levelAr: "متوسط",
    levelEn: "Intermediate",
    totalLessons: 20,
    durationHours: 3,
    totalXp: 1900,
    icon: "📈",
    accentFrom: "#15803d",
    accentTo: "#166534",
    outcomesAr: ["حساب هامش المساهمة لكل وحدة مباعة (Contribution Margin)", "توقع وتمديد مدة بقاء الشركة النقدية (Runway)", "بناء نموذج مالي واقعي لمدة 12 شهراً قادمة"],
    outcomesEn: ["Calculate net contribution margins per transaction", "Forecast and optimize company cash runway to reach profitability", "Construct an operational 12-month financial projection model"],
    realityAr: "إذا كانت الوحدة الواحدة تخسر أموالاً، فإن التوسع السريع يعني الإفلاس السريع.",
    realityEn: "If your unit economics lose money, scaling faster just accelerates bankruptcy.",
    badgeTitleAr: "مدير مالي للشركات الناشئة",
    badgeTitleEn: "Startup Finance Lead",
  },
  {
    id: 68,
    slug: "remote-team-hiring-leadership",
    order: 68,
    pillarId: 7,
    pillarNameAr: "ريادة الأعمال",
    pillarNameEn: "Entrepreneurship",
    titleAr: "توظيف وقيادة فرق العمل عن بُعد (Remote Leadership)",
    titleEn: "Hiring & Leading High-Output Remote Teams",
    descriptionAr: "كيف تختار أفضل الكفاءات العالمية، تبني ثقافة إنتاجية متزامنة وغير متزامنة، وتدير الموظفين بالنتائج.",
    descriptionEn: "Source top remote talent, build asynchronous communication habits, and manage by outcomes.",
    levelAr: "متوسط",
    levelEn: "Intermediate",
    totalLessons: 22,
    durationHours: 3.5,
    totalXp: 2000,
    icon: "🌐",
    accentFrom: "#4f46e5",
    accentTo: "#3730a3",
    outcomesAr: ["تصميم مقابلات عملية قائمة على اختبارات المهام الحقيقية", "بناء نظام تواصل غير متزامن يقلل الاجتماعات بنسبة 70%", "تحفيز الفريق والحفاظ على الروح المعنوية العالية عن بعد"],
    outcomesEn: ["Conduct practical paid trial projects to evaluate candidates objectively", "Implement asynchronous workflows slashing unnecessary Zoom meetings", "Cultivate psychological safety and high team morale across borders"],
    realityAr: "العمل عن بعد يحتاج توظيف أشخاص يتمتعون بالمسؤولية الذاتية ولا يحتاجون إلى من يراقب شاشاتهم.",
    realityEn: "Remote success demands hiring self-managing adults whom you measure by output, not hours.",
    badgeTitleAr: "قائد فرق عمل عن بُعد",
    badgeTitleEn: "Remote Team Leader",
  },
  {
    id: 69,
    slug: "ecommerce-store-supply-chain",
    order: 69,
    pillarId: 7,
    pillarNameAr: "ريادة الأعمال",
    pillarNameEn: "Entrepreneurship",
    titleAr: "تأسيس وإدارة التجارة الإلكترونية وسلاسل الإمداد",
    titleEn: "E-Commerce Setup & Supply Chain Logistics",
    descriptionAr: "من تصنيع أو استيراد المنتج، والتغليف، إلى الشحن، وتقليل المرتجعات، وتوفير تجربة استلام مبهرة للعميل.",
    descriptionEn: "Source products, manage inventory and warehousing, streamline shipping, and slash return rates.",
    levelAr: "مبتدئ",
    levelEn: "Beginner",
    totalLessons: 24,
    durationHours: 3.5,
    totalXp: 2000,
    icon: "📦",
    accentFrom: "#d97706",
    accentTo: "#92400e",
    outcomesAr: ["التفاوض مع الموردين ومصانع التغليف للحصول على أفضل سعر", "اختيار شركات الشحن الموثوقة وتقليل نسبة الفشل في التوصيل", "إدارة المخزون لمنع نفاد المنتجات أو تكدس الأموال راكدة"],
    outcomesEn: ["Negotiate with manufacturing suppliers for margin leverage", "Select reliable couriers and reduce failed delivery returns", "Implement reorder-point inventory controls preventing stockouts"],
    realityAr: "التجارة الإلكترونية ليست مجرد موقع إلكتروني؛ هي عمليات شحن وجودة منتج على أرض الواقع.",
    realityEn: "E-commerce is a physical fulfillment and customer service business first, website second.",
    badgeTitleAr: "رائد تجارة إلكترونية",
    badgeTitleEn: "E-Commerce Operator",
  },
  {
    id: 70,
    slug: "crisis-management-business-resilience",
    order: 70,
    pillarId: 7,
    pillarNameAr: "ريادة الأعمال",
    pillarNameEn: "Entrepreneurship",
    titleAr: "المرونة المؤسسية وإدارة الأزمات والتقلبات الاقتصادية",
    titleEn: "Crisis Management & Business Resilience",
    descriptionAr: "كيف تحمي شركتك في أوقات التضخم، تقلبات العملة، وتغيرات السوق المفاجئة وتخرج منها أكثر قوة.",
    descriptionEn: "Shield your business against currency devaluations, macroeconomic shocks, and operational crises.",
    levelAr: "متقدم",
    levelEn: "Advanced",
    totalLessons: 20,
    durationHours: 3,
    totalXp: 2100,
    icon: "🛡️",
    accentFrom: "#dc2626",
    accentTo: "#991b1b",
    outcomesAr: ["إعادة هيكلة التكاليف السريعة في أوقات الأزمات دون إيقاف النمو", "تنويع مصادر الدخل لحماية المشروع من الصدمات الفردية", "التواصل الشفاف مع الموظفين والعملاء للحفاظ على الثقة"],
    outcomesEn: ["Execute emergency cost restructuring while protecting core revenue", "Hedge business cash reserves against currency devaluations", "Communicate with transparency to preserve customer loyalty during turmoil"],
    realityAr: "الشركات العظيمة لا تبنى في أوقات الرخاء، بل تصقل وتكتسح الأسواق أثناء الأزمات.",
    realityEn: "Great companies are forged and capture massive market share in economic downturns.",
    badgeTitleAr: "قائد مرونة مؤسسية",
    badgeTitleEn: "Resilient Leader",
  },

  // --- PILLAR 8: CYBERSECURITY & PRIVACY (71-80) ---
  {
    id: 71,
    slug: "personal-cyber-hygiene-opsec",
    order: 71,
    pillarId: 8,
    pillarNameAr: "الأمن السيبراني",
    pillarNameEn: "Cybersecurity",
    titleAr: "الوعي السيبراني والأمان الرقمي الشخصي (OPSEC)",
    titleEn: "Personal Cybersecurity & Digital Hygiene",
    descriptionAr: "تأمين حساباتك البنكية، إيميلاتك، وأجهزتك من الاختراق، التجسس، وسرقة الهوية الرقمية.",
    descriptionEn: "Harden your personal bank accounts, communications, and laptops against identity theft and surveillance.",
    levelAr: "مبتدئ",
    levelEn: "Beginner",
    totalLessons: 20,
    durationHours: 2.5,
    totalXp: 1600,
    icon: "🔒",
    accentFrom: "#0284c7",
    accentTo: "#1e293b",
    outcomesAr: ["تطبيق المصادقة الثنائية القوية (2FA via Hardware / Apps)", "إنشاء وإدارة كلمات مرور لا يمكن تخمينها بمولدات مشفرة", "فحص الروابط المشبوهة وحماية الهواتف من برمجيات التجسس"],
    outcomesEn: ["Enforce hardware/authenticator-based Multi-Factor Authentication", "Manage master password vaults eliminating password reuse", "Detect spyware vectors and inspect suspicious shortened URLs"],
    realityAr: "أقوى نظام أمان في العالم يمكن اختراقه إذا ضغطت على رابط احتيالي واحد بحسن نية.",
    realityEn: "The strongest corporate firewall is instantly bypassed if a user clicks a malicious link.",
    badgeTitleAr: "محترف الأمان الرقمي",
    badgeTitleEn: "Cyber Hygiene Specialist",
  },
  {
    id: 72,
    slug: "computer-networking-fundamentals",
    order: 72,
    pillarId: 8,
    pillarNameAr: "الأمن السيبراني",
    pillarNameEn: "Cybersecurity",
    titleAr: "أساسيات شبكات الحاسب والبروتوكولات (Networking)",
    titleEn: "Computer Networking Fundamentals",
    descriptionAr: "فهم كيف تنتقل البيانات عبر الإنترنت: بروتوكولات TCP/IP و DNS و HTTP وحزم البيانات والراوترات.",
    descriptionEn: "Understand how packets traverse the internet: TCP/IP stack, DNS resolution, and routing protocols.",
    levelAr: "مبتدئ",
    levelEn: "Beginner",
    totalLessons: 24,
    durationHours: 3.5,
    totalXp: 1900,
    icon: "🌐",
    accentFrom: "#0d9488",
    accentTo: "#115e59",
    outcomesAr: ["فهم طبقات نموذج OSI السبعة وكيفية عملها", "تحليل حركة حزم البيانات باستخدام أداة Wireshark", "فهم خوادم الـ Proxy والـ VPN وجدران الحماية (Firewalls)"],
    outcomesEn: ["Master the 7 layers of the OSI model and packet flow", "Capture and inspect live network packet traces with Wireshark", "Configure subnets, NAT, proxies, and perimeter firewalls"],
    realityAr: "لا يمكنك حماية أو اختبار ما لا تفهم كيف يعمل أصلاً على مستوى الشبكة.",
    realityEn: "You cannot protect or penetration-test systems without understanding networking fundamentals.",
    badgeTitleAr: "أخصائي شبكات معتمد",
    badgeTitleEn: "Networking Foundations Specialist",
  },
  {
    id: 73,
    slug: "ethical-hacking-penetration-testing",
    order: 73,
    pillarId: 8,
    pillarNameAr: "الأمن السيبراني",
    pillarNameEn: "Cybersecurity",
    titleAr: "مقدمة في الاختبار الاختراقي الأخلاقي (Ethical Hacking)",
    titleEn: "Ethical Hacking & Penetration Testing Basics",
    descriptionAr: "تعلم التفكير كالمخترق لاكتشاف الثغرات في الأنظمة وإغلاقها قبل أن يستغلها القراصنة المخرّبون.",
    descriptionEn: "Learn attacker methodologies: reconnaissance, vulnerability scanning, and ethical exploit verification.",
    levelAr: "متوسط",
    levelEn: "Intermediate",
    totalLessons: 26,
    durationHours: 4.5,
    totalXp: 2400,
    icon: "🕵️",
    accentFrom: "#dc2626",
    accentTo: "#450a0a",
    outcomesAr: ["فحص الشبكات واكتشاف المنافذ المفتوحة بـ Nmap", "استخدام أدوات اختبار الاختراق الأخلاقي في بيئات افتراضية معزولة", "كتابة تقارير الثغرات المهنية لفرق الأمان بالمؤسسات"],
    outcomesEn: ["Conduct comprehensive network and port discovery with Nmap", "Run authorized penetration probes inside sandbox lab targets", "Author actionable vulnerability assessment remediation reports"],
    realityAr: "القرصنة الأخلاقية تتطلب إذناً كتابياً صريحاً دائماً؛ الأمان الرقمي لحماية الناس وليس للإيذاء.",
    realityEn: "Penetration testing strictly requires explicit written authorization; ethical hacking protects.",
    badgeTitleAr: "فاحص أمني أخلاقي",
    badgeTitleEn: "Ethical Hacker",
  },
  {
    id: 74,
    slug: "cloud-security-essentials",
    order: 74,
    pillarId: 8,
    pillarNameAr: "الأمن السيبراني",
    pillarNameEn: "Cybersecurity",
    titleAr: "الأمان السحابي وحماية البنى التحتية (Cloud Security)",
    titleEn: "Cloud Security Essentials (AWS / GCP / Azure)",
    descriptionAr: "تأمين الخوادم وقواعد البيانات السحابية، إدارة الصلاحيات الصارمة، ومنع تسرب البيانات الحساسة.",
    descriptionEn: "Secure cloud buckets, databases, and VMs while enforcing least-privilege IAM policies.",
    levelAr: "متقدم",
    levelEn: "Advanced",
    totalLessons: 24,
    durationHours: 4,
    totalXp: 2300,
    icon: "☁️",
    accentFrom: "#0284c7",
    accentTo: "#0f172a",
    outcomesAr: ["تطبيق مبدأ الصلاحيات الأقل (Least Privilege IAM)", "تأمين حاويات التخزين السحابية (S3 / Storage Buckets)", "تفعيل التشفير أثناء التخزين والانتقال (At-Rest and In-Transit)"],
    outcomesEn: ["Enforce granular least-privilege IAM policies and roles", "Lock down cloud storage buckets against inadvertent public leaks", "Configure KMS customer-managed encryption at-rest and in-transit"],
    realityAr: "أغلب اختراقات السحابة ليست بسبب عيب في السحابة، بل بسبب أخطاء الإعداد البشري للصلاحيات.",
    realityEn: "Nearly all cloud data breaches stem from human misconfiguration of access permissions.",
    badgeTitleAr: "مهندس أمان سحابي",
    badgeTitleEn: "Cloud Security Specialist",
  },
  {
    id: 75,
    slug: "threat-detection-incident-response",
    order: 75,
    pillarId: 8,
    pillarNameAr: "الأمن السيبراني",
    pillarNameEn: "Cybersecurity",
    titleAr: "استجابة الحوادث واكتشاف التهديدات (Incident Response)",
    titleEn: "Incident Response & Threat Hunting",
    descriptionAr: "ماذا تفعل عند وقوع الاختراق؟ خطوات احتواء التهديد، جمع الأدلة الرقمية، واستعادة الأنظمة بسرعة.",
    descriptionEn: "Contain live security intrusions, conduct digital forensics, and recover operations without data loss.",
    levelAr: "متقدم",
    levelEn: "Advanced",
    totalLessons: 22,
    durationHours: 3.5,
    totalXp: 2300,
    icon: "🚨",
    accentFrom: "#ea580c",
    accentTo: "#9a3412",
    outcomesAr: ["عزل الأجهزة المصابة فوراً لمنع انتشار العدوى في الشبكة", "تحليل السجلات (Log Analysis) لمعرفة كيف دخل المهاجم", "بناء خطة استجابة للطوارئ تطبقها المؤسسة في ساعات"],
    outcomesEn: ["Isolate compromised hosts swiftly to halt lateral network movement", "Investigate server auth and kernel logs to trace initial attack vectors", "Execute tested Disaster Recovery playbooks under pressure"],
    realityAr: "السؤال في الأمان السيبراني ليس 'هل سنُستهدف؟' بل 'متى وكيف سنستجيب فوراً عند حدوثه؟'.",
    realityEn: "In cybersecurity, it is not if an incident occurs, but how rapidly your team detects and neutralizes it.",
    badgeTitleAr: "خبير استجابة الحوادث",
    badgeTitleEn: "Incident Responder",
  },
  {
    id: 76,
    slug: "endpoint-enterprise-security",
    order: 76,
    pillarId: 8,
    pillarNameAr: "الأمن السيبراني",
    pillarNameEn: "Cybersecurity",
    titleAr: "أمان أجهزة الموظفين والشركات (Endpoint Security)",
    titleEn: "Enterprise Endpoint Security & EDR",
    descriptionAr: "حماية لابتوبات وهواتف الموظفين، منع برمجيات الفدية (Ransomware)، وتأمين بيئة العمل الهجينة.",
    descriptionEn: "Defend workforce laptops and mobile devices against ransomware, malware, and lateral threats.",
    levelAr: "متوسط",
    levelEn: "Intermediate",
    totalLessons: 20,
    durationHours: 3,
    totalXp: 2000,
    icon: "💻",
    accentFrom: "#334155",
    accentTo: "#0f172a",
    outcomesAr: ["تثبيت وتكوين أنظمة EDR لمراقبة السلوك المريب للأجهزة", "تشفير الأقراص الصلبة بالكامل (BitLocker / FileVault)", "منع تسرب البيانات عبر وحدات الـ USB والملفات الخارجية"],
    outcomesEn: ["Deploy Endpoint Detection & Response (EDR) sensors", "Enforce full-disk encryption across enterprise fleets", "Implement removable media controls preventing data exfiltration"],
    realityAr: "جهاز لابتوب واحد لموظف يفقد في مقهى قد يكلف الشركة ملايين إذا لم تكن البيانات مشفرة.",
    realityEn: "A single lost employee laptop can cost a company millions if unencrypted.",
    badgeTitleAr: "أخصائي حماية الأنظمة",
    badgeTitleEn: "Endpoint Security Specialist",
  },
  {
    id: 77,
    slug: "social-engineering-antiphishing",
    order: 77,
    pillarId: 8,
    pillarNameAr: "الأمن السيبراني",
    pillarNameEn: "Cybersecurity",
    titleAr: "الهندسة الاجتماعية والحماية من التصيد (Anti-Phishing)",
    titleEn: "Social Engineering & Anti-Phishing Defense",
    descriptionAr: "كشف حيل الخداع البشري: الإيميلات المزيفة، الاتصالات الاحتيالية، وانتحال شخصيات المديرين والزملاء.",
    descriptionEn: "Unmask manipulation tactics: spear-phishing emails, vishing calls, and CEO fraud scams.",
    levelAr: "مبتدئ",
    levelEn: "Beginner",
    totalLessons: 18,
    durationHours: 2.5,
    totalXp: 1600,
    icon: "🎣",
    accentFrom: "#e11d48",
    accentTo: "#9f1239",
    outcomesAr: ["التعرف على إيميلات التصيد الاحتيالي المتقدمة في ثوانٍ", "حماية الموظفين من هجمات انتحال شخصية المدير (CEO Fraud)", "تدريب الفرق على ثقافة الشك الإيجابي والتحقق قبل أي تحويل مالي"],
    outcomesEn: ["Spot sophisticated spoofed headers and spoofed domain tricks instantly", "Defend finance teams against wire-fraud CEO impersonation traps", "Instill a culture of out-of-band verification before funds are transferred"],
    realityAr: "أخطر ثغرة في أي منظومة أمنية هي دائماً العنصر البشري الذي يمكن خداعه بالعاطفة أو الخوف.",
    realityEn: "The easiest vulnerability to exploit is always human trust, urgency, or fear.",
    badgeTitleAr: "خبير مكافحة التصيد",
    badgeTitleEn: "Anti-Phishing Specialist",
  },
  {
    id: 78,
    slug: "data-privacy-gdpr-compliance",
    order: 78,
    pillarId: 8,
    pillarNameAr: "الأمن السيبراني",
    pillarNameEn: "Cybersecurity",
    titleAr: "حماية البيانات والخصوصية وقوانين GDPR والأنظمة",
    titleEn: "Data Privacy & GDPR Compliance",
    descriptionAr: "كيف تجمع بيانات المستخدمين بشكل قانوني، تحترم خصوصيتهم، وتتجنب الغرامات المالية الضخمة.",
    descriptionEn: "Comply with GDPR and data protection laws: user consent, deletion requests, and safe storage.",
    levelAr: "متوسط",
    levelEn: "Intermediate",
    totalLessons: 20,
    durationHours: 3,
    totalXp: 1900,
    icon: "📜",
    accentFrom: "#475569",
    accentTo: "#1e293b",
    outcomesAr: ["فهم متطلبات اللائحة العامة لحماية البيانات (GDPR)", "كتابة سياسة خصوصية واضحة وشروط استخدام منيعة", "تنفيذ حق النسيان ومسح بيانات العميل عند طلبه بسهولة"],
    outcomesEn: ["Navigate key GDPR tenets: lawful basis, consent, and processor agreements", "Draft transparent privacy policies and cookie consent banners", "Implement technical workflows fulfilling user data deletion requests"],
    realityAr: "احترام خصوصية المستخدم هو ميزة تنافسية تبني ثقة المشتري قبل أن تكون مجرد التزام قانوني.",
    realityEn: "Respecting user privacy is a commercial differentiator that inspires deep customer loyalty.",
    badgeTitleAr: "أخصائي خصوصية البيانات",
    badgeTitleEn: "Privacy Compliance Officer",
  },
  {
    id: 79,
    slug: "identity-access-management-iam",
    order: 79,
    pillarId: 8,
    pillarNameAr: "الأمن السيبراني",
    pillarNameEn: "Cybersecurity",
    titleAr: "إدارة الهويات والوصول الآمن للشركات (IAM & Zero-Trust)",
    titleEn: "Identity & Access Management (IAM & Zero-Trust)",
    descriptionAr: "تطبيق مبدأ 'عدم الثقة بأي أحد والتحقق دائماً' (Zero Trust) لتأمين الدخول للأنظمة والمواقع المؤسسية.",
    descriptionEn: "Implement Zero-Trust architectures: Single Sign-On (SSO), context-based access, and SCIM.",
    levelAr: "متقدم",
    levelEn: "Advanced",
    totalLessons: 22,
    durationHours: 3.5,
    totalXp: 2200,
    icon: "🔑",
    accentFrom: "#0891b2",
    accentTo: "#164e63",
    outcomesAr: ["ربط الدخول الموحد (SSO with Okta / Google Workspace)", "سحب الصلاحيات فوراً عند مغادرة أي موظف للشركة بنقرة واحدة", "إلزام الدخول بشروط أمان متقدمة حسب الجهاز والموقع الجغرافي"],
    outcomesEn: ["Configure enterprise Single Sign-On (SSO / SAML 2.0)", "Automate instant employee offboarding revoking credentials fleetwide", "Enforce adaptive contextual MFA based on device health and geolocation"],
    realityAr: "كلمة المرور وحدها ماتت؛ الهوية الرقمية المؤمنة بالسياق هي خط الدفاع الأول اليوم.",
    realityEn: "The perimeter is dead; contextual user identity is the true modern security border.",
    badgeTitleAr: "مهندس إدارة الهويات",
    badgeTitleEn: "IAM Specialist",
  },
  {
    id: 80,
    slug: "applied-cryptography-secure-comms",
    order: 80,
    pillarId: 8,
    pillarNameAr: "الأمن السيبراني",
    pillarNameEn: "Cybersecurity",
    titleAr: "التشفير العملي وتأمين الاتصالات الرقمية (Cryptography)",
    titleEn: "Applied Cryptography & Secure Communications",
    descriptionAr: "كيف يعمل التشفير المتماثل وغير المتماثل (AES, RSA, ECC)، وتأمين شهادات SSL/TLS والرسائل السرية.",
    descriptionEn: "Demystify modern cryptography: symmetric AES, asymmetric RSA/ECC, hashing, and TLS handshakes.",
    levelAr: "متقدم",
    levelEn: "Advanced",
    totalLessons: 22,
    durationHours: 3.5,
    totalXp: 2300,
    icon: "🔐",
    accentFrom: "#6366f1",
    accentTo: "#312e81",
    outcomesAr: ["فهم الفرق بين التشفير، الترميز، والـ Hashing", "إعداد وتجديد شهادات الأمان SSL/TLS دون أخطاء", "استخدام التشفير من طرف لطرف (End-to-End Encryption) للاتصالات الحساسة"],
    outcomesEn: ["Differentiate hashing, encoding, and symmetric/asymmetric encryption", "Configure robust TLS cipher suites and automated HTTPS renewals", "Deploy End-to-End Encrypted communication channels safely"],
    realityAr: "قاعدة التشفير الذهبية الأولى: لا تحاول أبداً كتابة خوارزمية تشفير خاصة بك؛ استخدم الخوارزميات القياسية المختبرة.",
    realityEn: "The cardinal rule of cryptography: never invent your own crypto; implement vetted standards.",
    badgeTitleAr: "خبير تشفير عملي",
    badgeTitleEn: "Applied Cryptographer",
  },

  // --- PILLAR 9: SOFT SKILLS & LEADERSHIP (81-90) ---
  {
    id: 81,
    slug: "art-of-persuasion-influence",
    order: 81,
    pillarId: 9,
    pillarNameAr: "المهارات الناعمة",
    pillarNameEn: "Soft Skills",
    titleAr: "فن الإقناع والتأثير القيادي الأخلاقي (Persuasion)",
    titleEn: "The Art of Ethical Persuasion & Influence",
    descriptionAr: "كيف تجعل أفكارك مقبولة، تكسب دعم مدرائك، وتقنع زملاءك وعملاءك بالموافقة على مقترحاتك بسهولة.",
    descriptionEn: "Master Robert Cialdini's principles of ethical influence to win buy-in for your ideas.",
    levelAr: "مبتدئ",
    levelEn: "Beginner",
    totalLessons: 20,
    durationHours: 2.5,
    totalXp: 1600,
    icon: "🗣️",
    accentFrom: "#f59e0b",
    accentTo: "#b45309",
    outcomesAr: ["استخدام مبادئ التأثير الستة (التبادل، الإثبات الاجتماعي، الندرة)", "صياغة الأفكار لتتوافق مع أولويات الطرف الآخر مباشرة", "بناء الكاريزما المهنية التي تفرض احترامك في أي جلسة"],
    outcomesEn: ["Leverage Cialdini's influence levers: reciprocity, social proof, and scarcity", "Frame ideas directly matching your stakeholder's self-interest", "Project quiet professional charisma commanding respect in meetings"],
    realityAr: "الإقناع ليس إجباراً للآخرين، بل مساعدتهم على اكتشاف لماذا قرارك يصب في مصلحتهم الحقيقية.",
    realityEn: "Persuasion is not manipulation; it is revealing how your proposal benefits all parties.",
    badgeTitleAr: "خبير إقناع وتأثير",
    badgeTitleEn: "Persuasion Specialist",
  },
  {
    id: 82,
    slug: "public-speaking-presentations",
    order: 82,
    pillarId: 9,
    pillarNameAr: "المهارات الناعمة",
    pillarNameEn: "Soft Skills",
    titleAr: "مهارات العرض والإلقاء والتحدث الجماهيري الواثق",
    titleEn: "Public Speaking & Confident Presentations",
    descriptionAr: "التغلب على رهبة التحدث أمام الجمهور، التحكم في نبرة الصوت، وتقديم عروض تقديمية تخطف القلوب والعقول.",
    descriptionEn: "Conquer stage fright, master vocal inflection, and deliver presentations that leave audiences inspired.",
    levelAr: "مبتدئ",
    levelEn: "Beginner",
    totalLessons: 22,
    durationHours: 3,
    totalXp: 1800,
    icon: "🎤",
    accentFrom: "#ea580c",
    accentTo: "#c2410c",
    outcomesAr: ["التحكم في توتر البداية في أول 60 ثانية من أي عرض", "استخدام لغة الجسد والتواصل البصري المؤثر", "تصميم شرائح عرض بصرية بسيطة لا تشتت الجمهور عن كلامك"],
    outcomesEn: ["Channel nervous adrenaline into commanding energy in the first 60 seconds", "Command physical presence with confident eye contact and open posture", "Design minimalist slide decks that amplify your message rather than distract"],
    realityAr: "التوتر قبل الحديث طبيعي تماماً حتى لأعظم الخطباء؛ السر في تحويل التوتر إلى حماس وطاقة.",
    realityEn: "Stage nervousness never fully vanishes; the secret is transforming tension into enthusiastic drive.",
    badgeTitleAr: "متحدث جماهيري واثق",
    badgeTitleEn: "Confident Speaker",
  },
  {
    id: 83,
    slug: "emotional-intelligence-workplace",
    order: 83,
    pillarId: 9,
    pillarNameAr: "المهارات الناعمة",
    pillarNameEn: "Soft Skills",
    titleAr: "الذكاء العاطفي في بيئات العمل (Emotional Intelligence)",
    titleEn: "Emotional Intelligence in the Workplace (EQ)",
    descriptionAr: "الوعي بذاتك، ضبط الانفعالات تحت الضغط، وقراءة مشاعر الآخرين لبناء علاقات عمل ناجحة ومريحة.",
    descriptionEn: "Develop self-awareness, emotional regulation under pressure, and empathy to navigate office dynamics.",
    levelAr: "مبتدئ",
    levelEn: "Beginner",
    totalLessons: 20,
    durationHours: 2.5,
    totalXp: 1700,
    icon: "🧠",
    accentFrom: "#0d9488",
    accentTo: "#0f766e",
    outcomesAr: ["السيطرة على ردات الفعل العاطفية في المواقف المستفزة", "فهم دوافع ومخاوف زملائك في العمل والتعاطف معهم", "بناء مناعة نفسية تمنع انتقال طاقة الأشخاص السلبيين إليك"],
    outcomesEn: ["Pause and choose calm responses rather than impulsive emotional reactions", "Decode unexpressed fears and underlying motivations of team members", "Maintain psychological boundaries shielding you from toxic workplace friction"],
    realityAr: "الذكاء العقلي (IQ) يجعلك تحصل على الوظيفة، لكن الذكاء العاطفي (EQ) هو الذي يجعلك تترقى وتقود.",
    realityEn: "Technical IQ gets you in the door; emotional EQ earns you promotions and leadership.",
    badgeTitleAr: "محترف الذكاء العاطفي",
    badgeTitleEn: "Emotional Intelligence Master",
  },
  {
    id: 84,
    slug: "high-stakes-salary-negotiation",
    order: 84,
    pillarId: 9,
    pillarNameAr: "المهارات الناعمة",
    pillarNameEn: "Soft Skills",
    titleAr: "التفاوض على العقود والرواتب وزيادة الدخل (Negotiation)",
    titleEn: "High-Stakes Salary & Deal Negotiation",
    descriptionAr: "كيف تطلب زيادة راتبك أو تتفاوض على عقدك الجديد للحصول على أعلى قيمة سوقية تستحقها دون إحراج.",
    descriptionEn: "Negotiate higher compensation and lucrative contracts with tactical empathy and zero awkwardness.",
    levelAr: "متوسط",
    levelEn: "Intermediate",
    totalLessons: 20,
    durationHours: 3,
    totalXp: 1900,
    icon: "💰",
    accentFrom: "#16a34a",
    accentTo: "#15803d",
    outcomesAr: ["معرفة القيمة السوقية الحقيقية لمهاراتك بالأرقام", "استخدام أسلوب كريس فوس (Chris Voss) في التفاوض التكتيكي", "التفاوض على المزايا غير المالية (العمل عن بعد، الإجازات، الحوافز)"],
    outcomesEn: ["Research accurate market benchmarks for your specific skillset", "Apply Chris Voss's tactical empathy and calibrated questioning techniques", "Negotiate non-monetary perks: remote flexibility, equity, and vacation time"],
    realityAr: "أنت لا تحصل على ما تستحقه في الحياة، بل تحصل على ما تتفاوض عليه بثقة واستعداد.",
    realityEn: "You don't get what you deserve in your career; you get what you negotiate with poise.",
    badgeTitleAr: "مفاوض محترف",
    badgeTitleEn: "Master Negotiator",
  },
  {
    id: 85,
    slug: "critical-thinking-structured-problem-solving",
    order: 85,
    pillarId: 9,
    pillarNameAr: "المهارات الناعمة",
    pillarNameEn: "Soft Skills",
    titleAr: "التفكير النقدي وحل المشكلات المعقدة (First Principles)",
    titleEn: "Critical Thinking & First-Principles Problem Solving",
    descriptionAr: "تفكيك المشاكل الصعبة إلى مبادئها الأولية وإيجاد حلول مبتكرة خارج الصندوق لا يراها الآخرون.",
    descriptionEn: "Deconstruct complex roadblocks down to fundamental truths and formulate innovative breakthroughs.",
    levelAr: "متوسط",
    levelEn: "Intermediate",
    totalLessons: 22,
    durationHours: 3,
    totalXp: 1900,
    icon: "🧩",
    accentFrom: "#0284c7",
    accentTo: "#0369a1",
    outcomesAr: ["التفكير من المبادئ الأولى (First Principles Thinking)", "تجنب التحيزات المعرفية الشائعة (Cognitive Biases)", "استخدام أشجار المشكلات (Issue Trees) للوصول للسبب الجذري"],
    outcomesEn: ["Think from First Principles instead of by superficial analogy", "Identify and bypass cognitive biases clouding analytical judgment", "Construct MECE hypothesis and root-cause issue trees"],
    realityAr: "أغلب الناس يقضون وقتاً طويلاً في حل المشكلة الخطأ؛ 90% من الحل هو تعريف المشكلة بدقة.",
    realityEn: "Most teams spend months solving the wrong problem; real mastery is defining the core dilemma.",
    badgeTitleAr: "مفكر نقدي معتمد",
    badgeTitleEn: "Critical Thinking Analyst",
  },
  {
    id: 86,
    slug: "assertive-communication-conflict-resolution",
    order: 86,
    pillarId: 9,
    pillarNameAr: "المهارات الناعمة",
    pillarNameEn: "Soft Skills",
    titleAr: "التواصل الحازم وحل النزاعات المهنية (Assertiveness)",
    titleEn: "Assertive Communication & Conflict Management",
    descriptionAr: "كيف تقول 'لا' بأدب دون الشعور بالذنب، وتدافع عن حقوقك وحدودك المهنية بهدوء واحترام متبادل.",
    descriptionEn: "Say 'no' professionally without guilt, set respectful boundaries, and de-escalate workplace conflict.",
    levelAr: "مبتدئ",
    levelEn: "Beginner",
    totalLessons: 20,
    durationHours: 2.5,
    totalXp: 1700,
    icon: "🛡️",
    accentFrom: "#4f46e5",
    accentTo: "#3730a3",
    outcomesAr: ["التفريق بين السلوك السلبي، الهجومي، والحازم المتزن", "رفض المهام الزائدة بأسلوب احترافي يتقبله مديرك", "إنهاء الخلافات مع الزملاء دون ترك أي ضغينة شخصية"],
    outcomesEn: ["Master assertive balance between passive compliance and aggressive friction", "Politely decline overloaded tasks by presenting competing priorities", "Resolve tense interpersonal disputes leaving professional respect intact"],
    realityAr: "الحزم ليس وقاحة؛ هو احترامك لوقتك وطاقتك مع احترام حقوق الطرف الآخر في نفس الوقت.",
    realityEn: "Assertiveness is not aggression; it is honoring your own dignity while respecting others.",
    badgeTitleAr: "محاور حازم ومحترف",
    badgeTitleEn: "Assertive Communicator",
  },
  {
    id: 87,
    slug: "business-storytelling-leaders",
    order: 87,
    pillarId: 9,
    pillarNameAr: "المهارات الناعمة",
    pillarNameEn: "Soft Skills",
    titleAr: "فن السرد القصصي المهني للقادة (Storytelling)",
    titleEn: "Business Storytelling for Leaders",
    descriptionAr: "كيف تحول الأرقام والبيانات الجافة إلى قصص حية تلهم فريقك، تشعل حماسهم، وتخلد في أذهان العملاء.",
    descriptionEn: "Transform dry data and corporate vision into compelling narrative arcs that inspire action.",
    levelAr: "متوسط",
    levelEn: "Intermediate",
    totalLessons: 20,
    durationHours: 2.5,
    totalXp: 1700,
    icon: "📖",
    accentFrom: "#d97706",
    accentTo: "#b45309",
    outcomesAr: ["بناء هيكل القصة الكلاسيكي (البطل، التحدي، التحول، الانتصار)", "تضمين الأرقام والإحصائيات داخل سياق إنساني مؤثر", "استخدام القصص في بيع المنتجات وتحفيز فرق العمل"],
    outcomesEn: ["Structure classic business story arcs: Struggle, Catalyst, and Transformation", "Wrap quantitative performance metrics inside human narratives", "Tell founder and case-study stories that drive conversion and team buy-in"],
    realityAr: "الناس ينسون 90% من الأرقام والشرائح، لكنهم لا ينسون أبداً قصة لمست قلوبهم وأذهانهم.",
    realityEn: "Audiences forget 90% of your data points; they never forget a well-told story.",
    badgeTitleAr: "حكواتي أعمال محترف",
    badgeTitleEn: "Business Storyteller",
  },
  {
    id: 88,
    slug: "career-transitions-adaptability",
    order: 88,
    pillarId: 9,
    pillarNameAr: "المهارات الناعمة",
    pillarNameEn: "Soft Skills",
    titleAr: "إدارة التغيير والتحول المهني الذكي (Career Pivoting)",
    titleEn: "Navigating Career Transitions & Adaptability",
    descriptionAr: "كيف تغير مجالك الوظيفي بسلاسة، تنقل خبراتك السابقة لمجالك الجديد، وتثبت نفسك بسرعة.",
    descriptionEn: "Pivot into a new lucrative industry smoothly by transferring your core superpowers.",
    levelAr: "مبتدئ",
    levelEn: "Beginner",
    totalLessons: 20,
    durationHours: 3,
    totalXp: 1800,
    icon: "🧭",
    accentFrom: "#0f766e",
    accentTo: "#115e59",
    outcomesAr: ["تحديد المهارات القابلة للنقل (Transferable Skills) بين المجالات", "إعادة صياغة سيرتك الذاتية لتبدو كخبير في المجال الجديد", "بناء خطة انتقال آمنة دون انقطاع دخلك الشهري"],
    outcomesEn: ["Inventory transferable skills that bridge your past background to new industries", "Rebrand your CV and narrative to position yourself as an authority in the new field", "Execute a bridge plan transitioning safely without sacrificing income stability"],
    realityAr: "تغيير المسار المهني ليس خسارة لسنواتك السابقة، بل ميزة تجعلك تملك نظرة أوسع من منافسيك.",
    realityEn: "A career pivot doesn't waste your past; interdisciplinary breadth is your ultimate superpower.",
    badgeTitleAr: "خبير التحول المهني",
    badgeTitleEn: "Career Pivot Strategist",
  },
  {
    id: 89,
    slug: "mentorship-coaching-culture",
    order: 89,
    pillarId: 9,
    pillarNameAr: "المهارات الناعمة",
    pillarNameEn: "Soft Skills",
    titleAr: "التوجيه والإرشاد وبناء الثقافة الإيجابية (Coaching)",
    titleEn: "Mentorship & Coaching for Managers",
    descriptionAr: "كيف تدرب وتطور أعضاء فريقك ليصبحوا قادة مستقلين، وتقدم لهم الملاحظات البناءة دون إحباطهم.",
    descriptionEn: "Coach team members into independent problem-solvers using structured mentoring and empathetic feedback.",
    levelAr: "متوسط",
    levelEn: "Intermediate",
    totalLessons: 20,
    durationHours: 2.5,
    totalXp: 1800,
    icon: "🌱",
    accentFrom: "#16a34a",
    accentTo: "#15803d",
    outcomesAr: ["استخدام نموذج GROW في جلسات التوجيه الفردية (1-on-1s)", "تقديم التغذية الراجعة الصادقة والمحفزة (Radical Candor)", "مساعدة الموظفين في وضع خطط تطور مهني تحقق أهدافهم"],
    outcomesEn: ["Facilitate high-impact 1-on-1 coaching dialogues using the GROW framework", "Deliver constructive feedback using Radical Candor (Caring personally, challenging directly)", "Empower team members to design personal development roadmaps"],
    realityAr: "القائد الحقيقي لا يقاس بعدد التابعين له، بل بعدد القادة الذين استطاع صناعتهم ودعمهم.",
    realityEn: "A great leader is measured not by how many followers they lead, but how many leaders they produce.",
    badgeTitleAr: "مرشد وقائد تمكين",
    badgeTitleEn: "Empowerment Coach",
  },
  {
    id: 90,
    slug: "strategic-networking-relationships",
    order: 90,
    pillarId: 9,
    pillarNameAr: "المهارات الناعمة",
    pillarNameEn: "Soft Skills",
    titleAr: "التشبيك المهني الذكي وبناء العلاقات الاستراتيجية",
    titleEn: "Strategic Networking & Genuine Relationship Building",
    descriptionAr: "كيف تبني شبكة علاقات قوية مع كبار الخبراء وأصحاب القرار دون أن تبدو متطفلاً أو مصلحجياً.",
    descriptionEn: "Build an authentic, high-value professional network by providing genuine value first.",
    levelAr: "مبتدئ",
    levelEn: "Beginner",
    totalLessons: 20,
    durationHours: 2.5,
    totalXp: 1700,
    icon: "🤝",
    accentFrom: "#0284c7",
    accentTo: "#0369a1",
    outcomesAr: ["حضور المؤتمرات والفعاليات والخروج بصداقات مهنية حقيقية", "تقديم القيمة والمساعدة قبل طلب أي شيء بالمقابل (Give First)", "الحفاظ على استمرار العلاقات لسنوات برسائل بسيطة ودورية"],
    outcomesEn: ["Navigate conferences and events forging authentic personal bonds", "Apply the 'Give First' principle connecting people and sharing resources generously", "Nurture long-term professional relationships through low-friction check-ins"],
    realityAr: "شبكة علاقاتك ليست بعدد بطاقات العمل التي تجمعها، بل بعدد الأشخاص المستعدين للرد على اتصالك في أي وقت.",
    realityEn: "Your network is not how many cards you collect, but how many leaders eagerly pick up your call.",
    badgeTitleAr: "خبير تشبيك استراتيجي",
    badgeTitleEn: "Strategic Networker",
  },

  // --- PILLAR 10: PRODUCTIVITY & PEAK MINDSET (91-100) ---
  {
    id: 91,
    slug: "atomic-habits-relentless-focus",
    order: 91,
    pillarId: 10,
    pillarNameAr: "الإنتاجية وإدارة الذات",
    pillarNameEn: "Productivity & Mind",
    titleAr: "بناء العادات الذرية والالتزام اليومي المستدام",
    titleEn: "Atomic Habits for Relentless Focus",
    descriptionAr: "كيف تجعل العادات الجيدة بديهية وسهلة، وتتخلص من العادات السلبية دون الحاجة لقوة إرادة خارقة.",
    descriptionEn: "Build effortless daily habits and eliminate bad routines using behavioral habit-stacking loops.",
    levelAr: "مبتدئ",
    levelEn: "Beginner",
    totalLessons: 22,
    durationHours: 3,
    totalXp: 1800,
    icon: "⚛️",
    accentFrom: "#10b981",
    accentTo: "#059669",
    outcomesAr: ["تطبيق قاعدة الدقيقتين للبدء في أصعب المهام بدون مقاومة", "تصميم بيئتك المحيطة لتجعل العادة الإيجابية هي الخيار الأسهل", "تتبع العادات اليومية والحفاظ على السلسلة دون انقطاع"],
    outcomesEn: ["Apply the 2-Minute Rule to shatter task-initiation resistance", "Architect your physical and digital environment to make good habits frictionless", "Maintain habit tracking streaks without feeling overwhelmed"],
    realityAr: "أنت لا ترتقي لمستوى أهدافك، بل تهبط لمستوى أنظمتك وعاداتك اليومية.",
    realityEn: "You do not rise to the level of your goals; you fall to the level of your systems.",
    badgeTitleAr: "معماري العادات الذرية",
    badgeTitleEn: "Habit Architect",
  },
  {
    id: 92,
    slug: "deep-work-flow-state-mastery",
    order: 92,
    pillarId: 10,
    pillarNameAr: "الإنتاجية وإدارة الذات",
    pillarNameEn: "Productivity & Mind",
    titleAr: "العمل العميق والدخول في حالة التدفق الذهني (Deep Work)",
    titleEn: "Deep Work & Flow State Mastery",
    descriptionAr: "كيف تنعزل تماماً عن المشتتات وتنجز في ساعتين من التركيز المطلق ما ينجزه غيرك في أسبوع كامل.",
    descriptionEn: "Eliminate context switching and access sustained 2-hour flow states of hyper-productive execution.",
    levelAr: "مبتدئ",
    levelEn: "Beginner",
    totalLessons: 20,
    durationHours: 2.5,
    totalXp: 1700,
    icon: "🧘‍♂️",
    accentFrom: "#0284c7",
    accentTo: "#0369a1",
    outcomesAr: ["محفزات الدخول السريع في حالة التدفق (Flow State Triggers)", "حماية فترات العمل العميق من الاجتماعات والرسائل الفورية", "التغلب على إدمان تفقد الهاتف كل بضع دقائق"],
    outcomesEn: ["Activate neurochemical flow state triggers reliably on command", "Guard scheduled Deep Work blocks from meeting interruptions", "Wean your brain off chronic notification-checking dopamine addiction"],
    realityAr: "القدرة على التركيز العميق أصبحت نادرة جداً اليوم، مما يجعل المتقن لها يملك ميزة تنافسية خارقة.",
    realityEn: "Deep focus has become so rare in a distracted world that mastering it is an economic cheat code.",
    badgeTitleAr: "محترف العمل العميق",
    badgeTitleEn: "Deep Work Specialist",
  },
  {
    id: 93,
    slug: "time-blocking-prioritization-eisenhower",
    order: 93,
    pillarId: 10,
    pillarNameAr: "الإنتاجية وإدارة الذات",
    pillarNameEn: "Productivity & Mind",
    titleAr: "إدارة الوقت وتحديد الأولويات الحقيقية (Time Blocking)",
    titleEn: "Time Blocking & Priority Architecture",
    descriptionAr: "تنظيم جدولك الأسبوعي بنظام الكتل الزمنية والتمييز الصارم بين المهم والعاجل بمصفوفة أيزنهاور.",
    descriptionEn: "Structure your weekly calendar with disciplined time-blocks and ruthless Eisenhower matrix filtering.",
    levelAr: "مبتدئ",
    levelEn: "Beginner",
    totalLessons: 20,
    durationHours: 2.5,
    totalXp: 1700,
    icon: "🗓️",
    accentFrom: "#0d9488",
    accentTo: "#0f766e",
    outcomesAr: ["تخطيط الأسبوع يوم الأحد في 30 دقيقة فقط", "حظر أوقات الراحة والرياضة أولاً في التقويم قبل مواعيد العمل", "تصفية المهام السطحية وتفويض ما لا يحتاج تدخلك"],
    outcomesEn: ["Conduct efficient 30-minute Sunday weekly planning rituals", "Block recovery, exercise, and sleep times first before work appointments", "Triage superficial busywork and delegate non-essential tasks"],
    realityAr: "إذا لم تخطط أنت ليومك، فسوف تقع أسيراً لخطط وأولويات الآخرين ورسائلهم.",
    realityEn: "If you don't design your day, you will inevitably live in other people's inbox priorities.",
    badgeTitleAr: "خبير هندسة الوقت",
    badgeTitleEn: "Time Blocking Architect",
  },
  {
    id: 94,
    slug: "curing-procrastination-biases",
    order: 94,
    pillarId: 10,
    pillarNameAr: "الإنتاجية وإدارة الذات",
    pillarNameEn: "Productivity & Mind",
    titleAr: "التغلب النهائي على التسويف والمماطلة (Procrastination)",
    titleEn: "Curing Chronic Procrastination",
    descriptionAr: "فهم الجذور النفسية للتسويف (الخوف من الفشل، المثالية المفرطة) واستخدام تقنيات البدء الفوري.",
    descriptionEn: "Unravel the psychological roots of procrastination—perfectionism and fear—and build bias for action.",
    levelAr: "مبتدئ",
    levelEn: "Beginner",
    totalLessons: 20,
    durationHours: 2.5,
    totalXp: 1700,
    icon: "⚡",
    accentFrom: "#e11d48",
    accentTo: "#9f1239",
    outcomesAr: ["كسر شلل البداية بتقسيم المهمة الضخمة لخطوات متناهية الصغر", "التخلي عن فخ المثالية وقبول إنجاز العمل بنسبة 80% وإطلاقه", "استخدام تقنية عد الـ 5 ثوانٍ للتحرك قبل أن يفكر عقلك في التراجع"],
    outcomesEn: ["Disarm starting paralysis by shrinking tasks down to ridiculously tiny micro-steps", "Escape the perfectionism trap by embracing shipping 'good enough' iterations", "Apply Mel Robbins' 5-Second Rule to execute before self-doubt intervenes"],
    realityAr: "التسويف ليس مشكلة كسل، بل مشكلة تنظيم مشاعر وقلق من النتيجة؛ الحل هو البدء بأصغر خطوة ممكنة.",
    realityEn: "Procrastination is an emotional regulation issue, not laziness; tiny momentum cures it.",
    badgeTitleAr: "قاهر التسويف",
    badgeTitleEn: "Procrastination Slayer",
  },
  {
    id: 95,
    slug: "energy-management-sleep-architecture",
    order: 95,
    pillarId: 10,
    pillarNameAr: "الإنتاجية وإدارة الذات",
    pillarNameEn: "Productivity & Mind",
    titleAr: "إدارة الطاقة الحيوية وجودة النوم والوقاية من الإرهاق",
    titleEn: "Bio-Energy Management & Sleep Architecture",
    descriptionAr: "كيف تحافظ على طاقتك متقدة طوال اليوم: تحسين دورات النوم، تنظيم الكافيين، وتفادي خمول ما بعد الظهر.",
    descriptionEn: "Optimize circadian rhythms, caffeine timing, and restorative sleep to maintain peak vitality.",
    levelAr: "مبتدئ",
    levelEn: "Beginner",
    totalLessons: 20,
    durationHours: 2.5,
    totalXp: 1600,
    icon: "⚡",
    accentFrom: "#16a34a",
    accentTo: "#166534",
    outcomesAr: ["ضبط الساعة البيولوجية والاستيقاظ بنشاط طبيعي دون منبه مزعج", "توقيت تناول القهوة لمنع هبوط الطاقة المفاجئ في منتصف اليوم", "طقوس الاسترخاء المسائي للحصول على نوم عميق ومريح"],
    outcomesEn: ["Synchronize circadian biology with morning sunlight for natural morning energy", "Time caffeine intake strategically to prevent 2 PM afternoon crashes", "Build an evening wind-down protocol that maximizes restorative deep and REM sleep"],
    realityAr: "إدارة الوقت لا فائدة منها إذا كنت مستيقظاً ولكن طاقتك الذهنية والجسدية منتهية.",
    realityEn: "Time management is completely useless if your physical and cognitive battery is empty.",
    badgeTitleAr: "محترف إدارة الطاقة الحيوية",
    badgeTitleEn: "Bio-Energy Specialist",
  },
  {
    id: 96,
    slug: "overcoming-imposter-syndrome",
    order: 96,
    pillarId: 10,
    pillarNameAr: "الإنتاجية وإدارة الذات",
    pillarNameEn: "Productivity & Mind",
    titleAr: "التحرر من متلازمة المحتال وبناء الثقة بالنفس (Imposter)",
    titleEn: "Overcoming Imposter Syndrome & Self-Doubt",
    descriptionAr: "إسكات الصوت الداخلي الذي يشكك في استحقاقك، وتقبل نجاحاتك كحق مكتسب بفضل جهدك وتطورك المستمر.",
    descriptionEn: "Silence chronic self-doubt, overcome feelings of fraudulence, and internalize your accomplishments.",
    levelAr: "مبتدئ",
    levelEn: "Beginner",
    totalLessons: 18,
    durationHours: 2.5,
    totalXp: 1600,
    icon: "🦁",
    accentFrom: "#d97706",
    accentTo: "#b45309",
    outcomesAr: ["فهم أن الشعور بعدم الكفاءة يصيب كبار الخبراء عند تجربة شيء جديد", "بناء 'ملف الفخر' لتوثيق إنجازاتك ورسائل الشكر التي تلقيتها", "التفريق بين حقيقة مهاراتك وبين مشاعر الشك المؤقتة"],
    outcomesEn: ["Realize that imposter syndrome paradoxically afflicts high-achieving learners most", "Build a tangible 'Evidence of Competence' dossier documenting your real wins", "Separate subjective emotional anxiety from objective proof of your skills"],
    realityAr: "شعورك بأنك لا تعرف كل شيء دليل على وعيك وتواضعك؛ لا أحد يعلم كل شيء، والجميع يتعلم أثناء السير.",
    realityEn: "Feeling like you don't know everything is proof of humility; everyone figures it out as they go.",
    badgeTitleAr: "واثق ومتحرر من الشك",
    badgeTitleEn: "Unshakable Confidence",
  },
  {
    id: 97,
    slug: "digital-minimalism-attention-protection",
    order: 97,
    pillarId: 10,
    pillarNameAr: "الإنتاجية وإدارة الذات",
    pillarNameEn: "Productivity & Mind",
    titleAr: "المينيماليزم الرقمي واستعادة التركيز (Digital Minimalism)",
    titleEn: "Digital Minimalism & Attention Protection",
    descriptionAr: "تطهير هاتفك وحاسوبك من فوضى الإشعارات، استعادة سيادتك على انتباهك، وتوديع التشتت المستمر.",
    descriptionEn: "Declutter digital noise, silence toxic notifications, and reclaim sovereignty over your focus.",
    levelAr: "مبتدئ",
    levelEn: "Beginner",
    totalLessons: 18,
    durationHours: 2.5,
    totalXp: 1600,
    icon: "📵",
    accentFrom: "#475569",
    accentTo: "#1e293b",
    outcomesAr: ["إلغاء 95% من الإشعارات غير الضرورية دون أن يفوتك شيء مهم", "تخصيص أوقات محددة لتصفح السوشيال ميديا وإغلاقها بعدها", "استعادة القدرة على قراءة الكتب والتركيز لساعات متصلة"],
    outcomesEn: ["Audit and disable 95% of intrusive app notifications safely", "Confine social media check-ins to intentional, pre-scheduled windows", "Rebuild the cognitive endurance to read books and ponder ideas deeply"],
    realityAr: "انتباهك هو أغلى عملة تملكها؛ إذا لم تحمه، فإن شركات السوشيال ميديا ستبيعه للمعلنين مجاناً.",
    realityEn: "Your attention is your most precious finite currency; protect it fiercely from algorithmic capture.",
    badgeTitleAr: "محترف المينيماليزم الرقمي",
    badgeTitleEn: "Digital Minimalist",
  },
  {
    id: 98,
    slug: "growth-mindset-psychological-grit",
    order: 98,
    pillarId: 10,
    pillarNameAr: "الإنتاجية وإدارة الذات",
    pillarNameEn: "Productivity & Mind",
    titleAr: "عقلية النمو والمرونة النفسية في مواجهة الفشل (Grit)",
    titleEn: "Growth Mindset & Psychological Resilience",
    descriptionAr: "تحويل الأخطاء والإخفاقات إلى وقود يدفعك للأمام، وبناء عزيمة حديدية لا تنكسر أمام الصعاب.",
    descriptionEn: "Reframe failures as high-leverage data feedback and develop unstoppable perseverance (Grit).",
    levelAr: "مبتدئ",
    levelEn: "Beginner",
    totalLessons: 20,
    durationHours: 2.5,
    totalXp: 1700,
    icon: "🌱",
    accentFrom: "#059669",
    accentTo: "#047857",
    outcomesAr: ["تطبيق مفهوم 'ليس بعد' (The Power of Yet) عند مواجهة صعوبة", "التعامل مع الرفض والانتقاد كفرصة مجانية للتعلم والتحسين", "بناء جلد نفسي ومرونة عالية تجعلك تقف أسرع بعد كل كبوة"],
    outcomesEn: ["Embrace Carol Dweck's 'Power of Yet' whenever facing steep learning curves", "Digest harsh rejection and feedback as free diagnostic roadmaps to mastery", "Cultivate mental antifragility where setbacks actually strengthen your resolve"],
    realityAr: "الناجح لم يكن أذكى من الفاشل، بل كان فقط الشخص الذي حاول مرة إضافية بعد أن استسلم الجميع.",
    realityEn: "The master has failed more times than the beginner has even attempted.",
    badgeTitleAr: "صاحب عقلية نمو حديدية",
    badgeTitleEn: "Growth Mindset Master",
  },
  {
    id: 99,
    slug: "decision-making-under-stress",
    order: 99,
    pillarId: 10,
    pillarNameAr: "الإنتاجية وإدارة الذات",
    pillarNameEn: "Productivity & Mind",
    titleAr: "اتخاذ القرارات الحكيمة تحت الضغط الشديد (Mental Models)",
    titleEn: "Decision Making Under Pressure & Mental Models",
    descriptionAr: "نماذج التفكير الذهنية لكبار المستثمرين والقادة لاتخاذ قرارات سليمة عندما تكون المخاطر عالية والوقت ضيق.",
    descriptionEn: "Master mental models (Inversion, Second-Order Thinking) to make clear decisions under intense pressure.",
    levelAr: "متوسط",
    levelEn: "Intermediate",
    totalLessons: 20,
    durationHours: 3,
    totalXp: 1800,
    icon: "⚖️",
    accentFrom: "#0284c7",
    accentTo: "#1d4ed8",
    outcomesAr: ["استخدام نموذج التفكير العكسي (Inversion: كيف نضمن الفشل ونتجنبه؟)", "حساب عواقب الدرجة الثانية والثالثة لأي قرار قبل اتخاذه", "التمييز بين القرارات ذات الاتجاه الواحد (Reversible vs Irreversible Doors)"],
    outcomesEn: ["Apply Inversion modeling: map failure modes to safeguard success", "Evaluate second-and-third-order consequences before committing resources", "Classify Type 1 (irreversible) vs Type 2 (reversible) decisions for rapid execution"],
    realityAr: "القرار الجيد يقاس بجودة التفكير والبيانات وقت اتخاذه، وليس فقط بالحظ العشوائي للنتيجة.",
    realityEn: "Decision quality is judged by the rigor of your process, not random lucky outcomes.",
    badgeTitleAr: "صانع قرارات حكيمة",
    badgeTitleEn: "Strategic Decision Maker",
  },
  {
    id: 100,
    slug: "life-architecture-sustainable-harmony",
    order: 100,
    pillarId: 10,
    pillarNameAr: "الإنتاجية وإدارة الذات",
    pillarNameEn: "Productivity & Mind",
    titleAr: "بوصلة الحياة والتوازن المهني والشخصي المستدام",
    titleEn: "Life Architecture & Sustainable Work-Life Harmony",
    descriptionAr: "تصميم حياة متوازنة تجمع بين النجاح المالي والمهني، الصحة الجسدية، والعلاقات الأسرية الدافئة دون صراع.",
    descriptionEn: "Architect an intentional life balancing financial ambition, vibrant physical health, and deep relationships.",
    levelAr: "مبتدئ",
    levelEn: "Beginner",
    totalLessons: 22,
    durationHours: 3,
    totalXp: 1900,
    icon: "🌟",
    accentFrom: "#0f766e",
    accentTo: "#04342c",
    outcomesAr: ["رسم بوصلة الحياة الشخصية وتحديد تعريفك الحقيقي للنجاح", "وضع أهداف سنوية متسقة مع صحتك وعائلتك وليس فقط حسابك البنكي", "الاستمتاع بالرحلة واللحظة الحاضرة بدلاً من تأجيل السعادة إلى المستقبل"],
    outcomesEn: ["Define your authentic, personal scorecard for life success", "Set holistic yearly milestones honoring physical health, loved ones, and career", "Cultivate presence and joy during the daily climb rather than deferring happiness"],
    realityAr: "ما فائدة أن تكسب كل أموال العالم إذا خسرت صحتك وراحة بالك وعائلتك في الطريق؟ التوازن هو القمة الحقيقية.",
    realityEn: "Winning in career while going bankrupt in health or relationships is losing; true mastery is sustainable harmony.",
    badgeTitleAr: "معماري الحياة المتوازنة",
    badgeTitleEn: "Life Architecture Master",
  },
];
