import type { Track100 } from "./tracks100";

export const TRACKS_1_50: Track100[] = [
  // --- PILLAR 1: AI (1-10) ---
  {
    id: 1,
    slug: "prompt-engineering-mastery",
    order: 1,
    pillarId: 1,
    pillarNameAr: "الذكاء الاصطناعي",
    pillarNameEn: "AI & Prompts",
    titleAr: "هندسة الأوامر المتقدمة (Prompt Engineering)",
    titleEn: "Advanced Prompt Engineering",
    descriptionAr: "تعلم صياغة الأوامر بدقة استثنائية للتحكم في ChatGPT و Claude و Gemini واستخراج نتائج خارقة.",
    descriptionEn: "Master prompt crafting to control ChatGPT, Claude, and Gemini with surgical precision.",
    levelAr: "مبتدئ",
    levelEn: "Beginner",
    totalLessons: 24,
    durationHours: 3,
    totalXp: 1800,
    icon: "⚡",
    accentFrom: "#059669",
    accentTo: "#0d9488",
    outcomesAr: ["صياغة برومبتات احترافية من أول مرة", "استخدام Few-shot و Chain-of-Thought", "تقليل الهلوسة واستخراج بيانات منظمة"],
    outcomesEn: ["Write high-precision prompts instantly", "Leverage Few-shot & Chain-of-Thought prompting", "Eliminate hallucinations and extract structured data"],
    realityAr: "هندسة الأوامر مهارة تحتاج تدريباً مستمراً وتفكير منطقي، وليست مجرد سحر تلقائي.",
    realityEn: "Prompting requires logical thinking and practice, not magic copy-pasting.",
    badgeTitleAr: "مهندس أوامر معتمد",
    badgeTitleEn: "Certified Prompt Engineer",
  },
  {
    id: 2,
    slug: "autonomous-ai-agents",
    order: 2,
    pillarId: 1,
    pillarNameAr: "الذكاء الاصطناعي",
    pillarNameEn: "AI & Prompts",
    titleAr: "وكلاء الذكاء الاصطناعي المستقلون (AI Agents)",
    titleEn: "Autonomous AI Agents",
    descriptionAr: "بناء وإطلاق وكلاء أذكياء ينفذون المهام المعقدة نيابة عنك بشكل آلي.",
    descriptionEn: "Build and deploy multi-step AI agents that execute complex workflows autonomously.",
    levelAr: "متوسط",
    levelEn: "Intermediate",
    totalLessons: 22,
    durationHours: 4,
    totalXp: 2200,
    icon: "🤖",
    accentFrom: "#0d9488",
    accentTo: "#0284c7",
    outcomesAr: ["فهم معمارية الوكلاء المستقلين", "ربط الوكيل بأدوات التصفح واستدعاء الـ APIs", "أتمتة سلاسل أعمال كاملة"],
    outcomesEn: ["Understand autonomous agent architectures", "Connect agents to tools and external APIs", "Automate complete business workflows"],
    realityAr: "الوكلاء يحتاجون مراقبة حدودية واضحة لتجنب الحلقات اللانهائية والأخطاء غير المقصودة.",
    realityEn: "Agents need strict boundary guardrails to avoid runaway executions.",
    badgeTitleAr: "معماري وكلاء الـ AI",
    badgeTitleEn: "AI Agent Architect",
  },
  {
    id: 3,
    slug: "ai-media-midjourney",
    order: 3,
    pillarId: 1,
    pillarNameAr: "الذكاء الاصطناعي",
    pillarNameEn: "AI & Prompts",
    titleAr: "توليد الصور والميديا الاحترافية (Midjourney & Flux)",
    titleEn: "AI Image & Visuals Generation",
    descriptionAr: "تحويل خيالك لصور إعلانية وتصاميم سينمائية فائقة الدقة باستخدام Midjourney و Flux.",
    descriptionEn: "Transform ideas into photorealistic commercial imagery with Midjourney and Flux.",
    levelAr: "مبتدئ",
    levelEn: "Beginner",
    totalLessons: 20,
    durationHours: 3,
    totalXp: 1600,
    icon: "🎨",
    accentFrom: "#0f766e",
    accentTo: "#0369a1",
    outcomesAr: ["التحكم بالإضاءة والعدسات وزوايا الكاميرا", "توليد صور متسقة الشخصيات والأسلوب", "تصميم مواد تسويقية للعلامات التجارية"],
    outcomesEn: ["Control lighting, lenses, and cinematic compositions", "Create consistent character and style assets", "Design marketing materials for brands"],
    realityAr: "توليد الصورة يستغرق ثوانٍ، لكن ضبط التفاصيل المعقدة يتطلب ذوقاً بصرياً وصياغة متكررة.",
    realityEn: "Generating takes seconds, but consistent fine details require aesthetic taste and iterations.",
    badgeTitleAr: "فنان ميديا بالـ AI",
    badgeTitleEn: "AI Visual Artist",
  },
  {
    id: 4,
    slug: "ai-video-creation",
    order: 4,
    pillarId: 1,
    pillarNameAr: "الذكاء الاصطناعي",
    pillarNameEn: "AI & Prompts",
    titleAr: "صناعة الفيديو والأنيميشن بالذكاء الاصطناعي",
    titleEn: "AI Video Creation & Animation",
    descriptionAr: "إنتاج فيديوهات تسويقية وسينمائية كاملة باستخدام أدوات Runway و Kling و Pika.",
    descriptionEn: "Produce viral marketing and cinematic video clips using Runway, Kling, and Pika.",
    levelAr: "متوسط",
    levelEn: "Intermediate",
    totalLessons: 25,
    durationHours: 4,
    totalXp: 2000,
    icon: "🎬",
    accentFrom: "#0284c7",
    accentTo: "#4f46e5",
    outcomesAr: ["تحريك الصور الثابتة بنعومة فائقة", "صناعة إعلانات فيديو بدون كاميرا أو استوديو", "دمج الأصوات والتعليق الصوتي المولّد"],
    outcomesEn: ["Animate static images smoothly", "Create commercial videos without camera or studio", "Synchronize AI voiceovers and sound design"],
    realityAr: "فيديو الذكاء الاصطناعي يتطور أسبوعياً؛ التركيز هنا على المبادئ الإخراجية وليس أداة واحدة.",
    realityEn: "AI video tools evolve rapidly; focus on visual storytelling principles rather than single tools.",
    badgeTitleAr: "مخرج فيديو بالـ AI",
    badgeTitleEn: "AI Video Director",
  },
  {
    id: 5,
    slug: "ai-workplace-productivity",
    order: 5,
    pillarId: 1,
    pillarNameAr: "الذكاء الاصطناعي",
    pillarNameEn: "AI & Prompts",
    titleAr: "مضاعفة إنتاجية العمل اليومي بالذكاء الاصطناعي",
    titleEn: "AI Workplace Productivity",
    descriptionAr: "كيف تنجز عمل 8 ساعات في ساعتين فقط باستخدام الذكاء الاصطناعي في الإيميلات، التقارير والاجتماعات.",
    descriptionEn: "Cut your workday in half by automating emails, reports, summaries, and meeting notes.",
    levelAr: "مبتدئ",
    levelEn: "Beginner",
    totalLessons: 18,
    durationHours: 2.5,
    totalXp: 1500,
    icon: "⏱️",
    accentFrom: "#10b981",
    accentTo: "#059669",
    outcomesAr: ["تلخيص مئات الصفحات والاجتماعات بثوانٍ", "كتابة ردود بريد احترافية مخصصة فوراً", "صياغة عروض تقديمية وجداول تلقائية"],
    outcomesEn: ["Summarize long reports and meetings in seconds", "Draft executive emails instantly", "Automate presentations and spreadsheets"],
    realityAr: "الذكاء الاصطناعي لا يعفيك من المراجعة البشرية للمعلومات الحساسة.",
    realityEn: "AI boosts speed, but critical numbers and claims still require human sanity checks.",
    badgeTitleAr: "محترف الإنتاجية الذكية",
    badgeTitleEn: "AI Productivity Specialist",
  },
  {
    id: 6,
    slug: "no-code-ai-apps",
    order: 6,
    pillarId: 1,
    pillarNameAr: "الذكاء الاصطناعي",
    pillarNameEn: "AI & Prompts",
    titleAr: "بناء تطبيقات ذكية بدون برمجة (No-Code AI)",
    titleEn: "No-Code AI App Building",
    descriptionAr: "ربط النماذج اللغوية بمنصات Make و Zapier و Airtable لبناء أنظمة وحلول تجارية.",
    descriptionEn: "Connect LLMs to Make, Zapier, and Airtable to build automated enterprise apps without code.",
    levelAr: "متوسط",
    levelEn: "Intermediate",
    totalLessons: 24,
    durationHours: 3.5,
    totalXp: 2100,
    icon: "🧩",
    accentFrom: "#0d9488",
    accentTo: "#2563eb",
    outcomesAr: ["إنشاء أنظمة استقبال ومعالجة طلبات العملاء بالـ AI", "أتمتة النشر عبر منصات التواصل", "بناء قواعد بيانات ذكية ذاتية التحديث"],
    outcomesEn: ["Build automated AI customer ticket triage systems", "Automate multi-platform content publishing", "Construct self-updating smart databases"],
    realityAr: "أدوات No-Code أسرع في البداية لكنها قد تصبح مكلفة مع ملايين العمليات شهرياً.",
    realityEn: "No-Code is ultra-fast to ship, but high transaction volumes eventually require custom code.",
    badgeTitleAr: "مطوّر حلول بدون كود",
    badgeTitleEn: "No-Code AI Builder",
  },
  {
    id: 7,
    slug: "local-llms-open-source",
    order: 7,
    pillarId: 1,
    pillarNameAr: "الذكاء الاصطناعي",
    pillarNameEn: "AI & Prompts",
    titleAr: "تشغيل النماذج المحلية والسرية (Local LLMs)",
    titleEn: "Running Local & Private LLMs",
    descriptionAr: "تشغيل نماذج مثل Llama و DeepSeek و Mistral على جهازك أو خادمك الخاص بأمان وخصوصية 100%.",
    descriptionEn: "Run models like Llama, DeepSeek, and Mistral locally for 100% data privacy and zero API fees.",
    levelAr: "متقدم",
    levelEn: "Advanced",
    totalLessons: 20,
    durationHours: 3.5,
    totalXp: 2400,
    icon: "🔒",
    accentFrom: "#1e293b",
    accentTo: "#0f766e",
    outcomesAr: ["تثبيت وإدارة Ollama و LM Studio", "دمج النماذج المحلية في تطبيقات العمل", "حماية بيانات الشركة من التسرب السحابي"],
    outcomesEn: ["Install and configure Ollama and LM Studio", "Integrate private models into local software", "Protect enterprise data from cloud exposure"],
    realityAr: "تحتاج إلى عتاد جيد (معالج رسومي VRAM كافٍ) لتشغيل النماذج الكبيرة بسرعة مرضية.",
    realityEn: "Requires reasonable GPU VRAM to run large models at responsive speeds.",
    badgeTitleAr: "خبير النماذج المحلية",
    badgeTitleEn: "Local AI Specialist",
  },
  {
    id: 8,
    slug: "ai-chatbots-business",
    order: 8,
    pillarId: 1,
    pillarNameAr: "الذكاء الاصطناعي",
    pillarNameEn: "AI & Prompts",
    titleAr: "بناء روبوتات محادثة للشركات (RAG Chatbots)",
    titleEn: "Building Business RAG Chatbots",
    descriptionAr: "صناعة بوتات محادثة تفهم كتيبات ومنتجات الشركة بدقة عبر استرجاع المعرفة المعزز (RAG).",
    descriptionEn: "Build chatbots trained on proprietary company docs using Retrieval-Augmented Generation.",
    levelAr: "متقدم",
    levelEn: "Advanced",
    totalLessons: 26,
    durationHours: 4.5,
    totalXp: 2500,
    icon: "💬",
    accentFrom: "#0369a1",
    accentTo: "#1d4ed8",
    outcomesAr: ["فهم قواعد البيانات المتجهية (Vector DBs)", "بناء نظام يجيب استناداً لملفات PDF والوثائق", "منع الإجابات الخاطئة عن منتجات الشركة"],
    outcomesEn: ["Understand Vector Embeddings and DBs", "Build systems answering strictly from PDFs and manuals", "Eliminate inaccurate pricing and product hallucinations"],
    realityAr: "جودة الـ RAG تعتمد أولاً وأخيراً على جودة تنظيف وتنسيق الملفات المصدرية.",
    realityEn: "RAG accuracy is directly proportional to how well source documents are cleaned.",
    badgeTitleAr: "مهندس شات بوت الشركات",
    badgeTitleEn: "Enterprise RAG Engineer",
  },
  {
    id: 9,
    slug: "ai-copywriting-scripts",
    order: 9,
    pillarId: 1,
    pillarNameAr: "الذكاء الاصطناعي",
    pillarNameEn: "AI & Prompts",
    titleAr: "كتابة الإعلانات والسكريبتات بالـ AI",
    titleEn: "AI Copywriting & Scriptwriting",
    descriptionAr: "كتابة نصوص إعلانية وسيناريوهات فيديوهات تيك توك وريلز مقنعة وتجلب المبيعات.",
    descriptionEn: "Write high-converting ad copy and viral short-form video scripts powered by AI.",
    levelAr: "مبتدئ",
    levelEn: "Beginner",
    totalLessons: 20,
    durationHours: 2.5,
    totalXp: 1600,
    icon: "✍️",
    accentFrom: "#e11d48",
    accentTo: "#be185d",
    outcomesAr: ["صياغة خطافات (Hooks) تخطف الانتباه في أول 3 ثوانٍ", "توليد 10 أفكار إعلانية متباينة في دقائق", "تكييف النبرة لتطابق صوت البراند"],
    outcomesEn: ["Craft thumb-stopping 3-second hooks", "Generate 10 distinct ad angles in minutes", "Match any brand tone and voice accurately"],
    realityAr: "النصوص الجذابة تحتاج فهمك لنفسية العميل الحقيقية؛ الذكاء الاصطناعي يسرّع الصياغة فقط.",
    realityEn: "Winning copy comes from real customer empathy; AI simply accelerates the drafting.",
    badgeTitleAr: "كاتب إعلانات معتمد",
    badgeTitleEn: "Certified AI Copywriter",
  },
  {
    id: 10,
    slug: "ai-ethics-governance",
    order: 10,
    pillarId: 1,
    pillarNameAr: "الذكاء الاصطناعي",
    pillarNameEn: "AI & Prompts",
    titleAr: "أخلاقيات وقوانين وحوكمة الذكاء الاصطناعي",
    titleEn: "AI Ethics, Law & Governance",
    descriptionAr: "فهم حقوق الملكية الفكرية، قوانين الذكاء الاصطناعي العالمية، وتجنب المخاطر القانونية للشركات.",
    descriptionEn: "Navigate intellectual property, AI legal frameworks, and corporate compliance risks.",
    levelAr: "متوسط",
    levelEn: "Intermediate",
    totalLessons: 18,
    durationHours: 3,
    totalXp: 1700,
    icon: "⚖️",
    accentFrom: "#475569",
    accentTo: "#0f766e",
    outcomesAr: ["معرفة حقوق الملكية للمحتوى المولّد بالـ AI", "سياسات استخدام الذكاء الاصطناعي داخل المؤسسات", "حماية الأسرار التجارية والامتثال للأنظمة"],
    outcomesEn: ["Understand IP ownership of AI-generated assets", "Formulate internal corporate AI usage policies", "Safeguard trade secrets and maintain regulatory compliance"],
    realityAr: "القوانين تتغير باستمرار؛ المسار يركز على المبادئ الراسخة لحماية نفسك وعملك.",
    realityEn: "Regulations evolve rapidly; this track grounds you in evergreen risk-mitigation principles.",
    badgeTitleAr: "مستشار حوكمة الـ AI",
    badgeTitleEn: "AI Governance Specialist",
  },

  // --- PILLAR 2: CODING & DEV (11-20) ---
  {
    id: 11,
    slug: "modern-coding-fundamentals",
    order: 11,
    pillarId: 2,
    pillarNameAr: "البرمجة والتطوير",
    pillarNameEn: "Coding & Dev",
    titleAr: "أساسيات البرمجة والتفكير المنطقي الحديث",
    titleEn: "Modern Coding Fundamentals",
    descriptionAr: "مدخلك الصحيح لعالم البرمجة: المتغيرات، الدوال، الحلقات، وهياكل البيانات بأسلوب تفاعلي ومبسط.",
    descriptionEn: "Your foundation in software: variables, functions, loops, and data structures made simple.",
    levelAr: "مبتدئ",
    levelEn: "Beginner",
    totalLessons: 25,
    durationHours: 4,
    totalXp: 2000,
    icon: "💡",
    accentFrom: "#2563eb",
    accentTo: "#4f46e5",
    outcomesAr: ["التفكير كمهندس برمجيات لحل المشكلات", "فهم كيفية عمل الأكواد البرمجية خلف الكواليس", "كتابة برامج منطقية نظيفة وخالية من الأخطاء"],
    outcomesEn: ["Think algorithmically to break down problems", "Understand how programs execute under the hood", "Write clean, readable, bug-free logic"],
    realityAr: "البرمجة تحتاج صبراً وتدريباً على حل الألغاز، وليست حفظاً للقواعد.",
    realityEn: "Coding is about problem-solving grit, not memorizing syntax rules.",
    badgeTitleAr: "مبرمج أساسي معتمد",
    badgeTitleEn: "Foundations Developer",
  },
  {
    id: 12,
    slug: "frontend-react-nextjs",
    order: 12,
    pillarId: 2,
    pillarNameAr: "البرمجة والتطوير",
    pillarNameEn: "Coding & Dev",
    titleAr: "تطوير واجهات الويب الحديثة (React 19 & Next.js)",
    titleEn: "Frontend Mastery: React 19 & Next.js",
    descriptionAr: "بناء مواقع وتطبيقات ويب سريعة جداً وتفاعلية بأحدث معايير React 19 و Next.js App Router.",
    descriptionEn: "Build ultra-fast, interactive web apps using modern React 19 and Next.js App Router.",
    levelAr: "متوسط",
    levelEn: "Intermediate",
    totalLessons: 28,
    durationHours: 5,
    totalXp: 2600,
    icon: "⚛️",
    accentFrom: "#0284c7",
    accentTo: "#2563eb",
    outcomesAr: ["إتقان المكونات (Components) والـ Hooks الحديثة", "إدارة الحالة والتحميل السريع (SSR & Server Actions)", "تصميم واجهات متجاوبة وفاتنة مع Tailwind CSS"],
    outcomesEn: ["Master modern React Components & Hooks", "Handle state, SSR, and Server Actions", "Design responsive, responsive UI with Tailwind CSS"],
    realityAr: "تطوير الواجهات يتطلب اهتماماً بأدق تفاصيل تجربة المستخدم على الهواتف والأجهزة المختلفة.",
    realityEn: "Frontend requires relentless attention to mobile performance and edge-case rendering.",
    badgeTitleAr: "مطوّر واجهات محترف",
    badgeTitleEn: "Modern Frontend Engineer",
  },
  {
    id: 13,
    slug: "backend-nodejs-prisma",
    order: 13,
    pillarId: 2,
    pillarNameAr: "البرمجة والتطوير",
    pillarNameEn: "Coding & Dev",
    titleAr: "تطوير الخوادم وقواعد البيانات (Node.js & Prisma)",
    titleEn: "Backend APIs & Databases with Node.js",
    descriptionAr: "بناء المحرك الخلفي للتطبيقات: إنشاء الـ APIs، قواعد البيانات، والمصادقة الأمنية المشفرة.",
    descriptionEn: "Build rock-solid backend servers, RESTful APIs, relational databases, and secure JWT auth.",
    levelAr: "متوسط",
    levelEn: "Intermediate",
    totalLessons: 26,
    durationHours: 4.5,
    totalXp: 2500,
    icon: "⚙️",
    accentFrom: "#059669",
    accentTo: "#1e293b",
    outcomesAr: ["تصميم قواعد البيانات العلائقية بـ Prisma ORM", "تأمين الجلسات وكلمات المرور وتشفير الـ JWT", "معالجة الطلبات السريعة وحماية الخادم من الهجمات"],
    outcomesEn: ["Design relational schemas with Prisma ORM", "Implement secure JWT sessions and scrypt password hashing", "Protect APIs with rate-limiting and data validation"],
    realityAr: "الخوادم تحتاج حرصاً شديداً على أمان البيانات وعدم تسريب أي معلومات حساسة.",
    realityEn: "Backend development demands strict zero-trust security and data validation.",
    badgeTitleAr: "مهندس خوادم معتمد",
    badgeTitleEn: "Backend Systems Engineer",
  },
  {
    id: 14,
    slug: "python-automation-scripting",
    order: 14,
    pillarId: 2,
    pillarNameAr: "البرمجة والتطوير",
    pillarNameEn: "Coding & Dev",
    titleAr: "بايثون للأتمتة والمهام اليومية (Python Automation)",
    titleEn: "Python for Everyday Automation",
    descriptionAr: "كتابة سكربتات بايثون ذكية لقراءة الملفات، استخراج البيانات من المواقع، وإنجاز المهام الروتينية.",
    descriptionEn: "Write smart Python scripts to scrape web data, organize files, and automate repetitive tasks.",
    levelAr: "مبتدئ",
    levelEn: "Beginner",
    totalLessons: 22,
    durationHours: 3.5,
    totalXp: 1900,
    icon: "🐍",
    accentFrom: "#3b82f6",
    accentTo: "#eab308",
    outcomesAr: ["أتمتة التعامل مع ملفات Excel و PDF والـ CSV", "سحب البيانات من المواقع (Web Scraping)", "إرسال إشعارات وتقارير تلقائية على تيليجرام وإيميل"],
    outcomesEn: ["Automate Excel, CSV, and PDF processing", "Scrape dynamic web pages efficiently", "Dispatch automated Telegram and email notifications"],
    realityAr: "كتابة السكربتات سهلة مع بايثون، لكن احرص دائماً على احترام شروط استخدام المواقع المستهدفة.",
    realityEn: "Scripting is fun, but always adhere to legal scraping rate limits and site terms.",
    badgeTitleAr: "خبير أتمتة بايثون",
    badgeTitleEn: "Python Automation Specialist",
  },
  {
    id: 15,
    slug: "mobile-apps-flutter",
    order: 15,
    pillarId: 2,
    pillarNameAr: "البرمجة والتطوير",
    pillarNameEn: "Coding & Dev",
    titleAr: "تطوير تطبيقات الموبايل الشاملة (Flutter)",
    titleEn: "Cross-Platform Mobile Apps with Flutter",
    descriptionAr: "برمجة تطبيق موبايل واحد يعمل بكفاءة وسلاسة على هواتف Android و iOS بنظام Flutter و Dart.",
    descriptionEn: "Build high-performance native-feel apps for iOS and Android using Flutter & Dart.",
    levelAr: "متوسط",
    levelEn: "Intermediate",
    totalLessons: 28,
    durationHours: 5,
    totalXp: 2700,
    icon: "📱",
    accentFrom: "#0284c7",
    accentTo: "#06b6d4",
    outcomesAr: ["تصميم واجهات موبايل متجاوبة وسلسة 60fps", "ربط التطبيق بالخوادم واستقبال الإشعارات (Push Notifications)", "تجهيز التطبيق للنشر على Google Play و App Store"],
    outcomesEn: ["Craft 60fps fluid mobile UI layouts", "Connect to REST APIs and handle Push Notifications", "Prepare build bundles for App Store and Play Store"],
    realityAr: "نشر التطبيقات في المتاجر يحتاج التزاماً بسياسات وإرشادات Apple و Google الصارمة.",
    realityEn: "Store approval requires strict compliance with Google and Apple developer guidelines.",
    badgeTitleAr: "مطوّر تطبيقات موبايل",
    badgeTitleEn: "Mobile App Engineer",
  },
  {
    id: 16,
    slug: "api-architecture-design",
    order: 16,
    pillarId: 2,
    pillarNameAr: "البرمجة والتطوير",
    pillarNameEn: "Coding & Dev",
    titleAr: "تصميم وهندسة واجهات الـ API الاحترافية",
    titleEn: "Professional API Design & Architecture",
    descriptionAr: "كيف تبني واجهات برمجية نظيفة، سريعة، وسهلة الاستخدام للمطورين وفق أفضل المعايير العالمية.",
    descriptionEn: "Design clean, scalable, developer-friendly REST and GraphQL APIs following global standards.",
    levelAr: "متوسط",
    levelEn: "Intermediate",
    totalLessons: 20,
    durationHours: 3,
    totalXp: 2100,
    icon: "🔌",
    accentFrom: "#6366f1",
    accentTo: "#4f46e5",
    outcomesAr: ["معمارية الـ RESTful ومعايير الـ HTTP Status Codes", "تصميم الـ Rate Limiting والـ Caching والـ Versioning", "توثيق الـ APIs بأداة OpenAPI و Swagger"],
    outcomesEn: ["Master REST conventions and HTTP status semantics", "Implement rate-limiting, caching, and API versioning", "Generate automated API documentation with OpenAPI"],
    realityAr: "الـ API الجيد هو ما يفهمه المطور الآخر في 5 دقائق دون الحاجة لسؤالك.",
    realityEn: "A great API is one other engineers can integrate in 5 minutes without friction.",
    badgeTitleAr: "مهندس واجهات برمجية",
    badgeTitleEn: "API Architect",
  },
  {
    id: 17,
    slug: "cloud-devops-docker",
    order: 17,
    pillarId: 2,
    pillarNameAr: "البرمجة والتطوير",
    pillarNameEn: "Coding & Dev",
    titleAr: "أساسيات الحوسبة السحابية وDevOps (Docker & CI/CD)",
    titleEn: "Cloud & DevOps Fundamentals",
    descriptionAr: "حزم التطبيقات داخل حاويات Docker ونشرها تلقائياً على السيرفرات السحابية دون انقطاع الخدمة.",
    descriptionEn: "Containerize applications with Docker and build automated CI/CD deployment pipelines.",
    levelAr: "متقدم",
    levelEn: "Advanced",
    totalLessons: 24,
    durationHours: 4,
    totalXp: 2400,
    icon: "☁️",
    accentFrom: "#0284c7",
    accentTo: "#1e293b",
    outcomesAr: ["إنشاء وإدارة حاويات Docker بكفاءة", "إعداد خط أنابيب النشر التلقائي GitHub Actions", "مراقبة استقرار الخادم وسجلات الأخطاء الحية"],
    outcomesEn: ["Write lightweight, multi-stage Dockerfiles", "Setup automated GitHub Actions CI/CD pipelines", "Monitor live server metrics and crash logs"],
    realityAr: "الـ DevOps ليس مجرد أدوات، بل ثقافة عمل تضمن عدم تعطل الموقع أمام المستخدمين.",
    realityEn: "DevOps is an operational discipline to guarantee zero-downtime user availability.",
    badgeTitleAr: "مهندس DevOps معتمد",
    badgeTitleEn: "Certified DevOps Specialist",
  },
  {
    id: 18,
    slug: "secure-web-development",
    order: 18,
    pillarId: 2,
    pillarNameAr: "البرمجة والتطوير",
    pillarNameEn: "Coding & Dev",
    titleAr: "أمان وتأمين تطبيقات الويب (Web App Security)",
    titleEn: "Secure Web Application Development",
    descriptionAr: "حماية تطبيقاتك من أشهر الثغرات الأمنية مثل SQL Injection و XSS و CSRF وفق تصنيف OWASP Top 10.",
    descriptionEn: "Harden web apps against OWASP Top 10 exploits: SQLi, XSS, CSRF, and broken access controls.",
    levelAr: "متقدم",
    levelEn: "Advanced",
    totalLessons: 22,
    durationHours: 3.5,
    totalXp: 2300,
    icon: "🛡️",
    accentFrom: "#dc2626",
    accentTo: "#991b1b",
    outcomesAr: ["فهم آليات عمل الثغرات وكيف يستغلها المخترقون", "كتابة كود منيع وتطبيق سياسات CORS و CSP", "فحص الكود تلقائياً لاكتشاف الثغرات قبل النشر"],
    outcomesEn: ["Understand how hackers discover and weaponize flaws", "Enforce strict CSP, CORS, and sanitization headers", "Run automated SAST security scans before deployment"],
    realityAr: "الأمان يبدأ من السطر الأول في كتابة الكود، وليس شيئاً يضاف في نهاية المشروع.",
    realityEn: "Security is a design-time architectural priority, never an afterthought.",
    badgeTitleAr: "خبير أمان الويب",
    badgeTitleEn: "Web Security Specialist",
  },
  {
    id: 19,
    slug: "nocode-web-framer",
    order: 19,
    pillarId: 2,
    pillarNameAr: "البرمجة والتطوير",
    pillarNameEn: "Coding & Dev",
    titleAr: "تصميم مواقع الويب السريعة (Framer & Webflow)",
    titleEn: "Fast No-Code Web Design with Framer",
    descriptionAr: "تصميم وإطلاق مواقع هبوط تجارية تخطف الأبصار في ساعات معدودة دون كتابة سطر كود واحد.",
    descriptionEn: "Design and launch visually stunning, responsive landing pages in hours using Framer.",
    levelAr: "مبتدئ",
    levelEn: "Beginner",
    totalLessons: 20,
    durationHours: 3,
    totalXp: 1700,
    icon: "⚡",
    accentFrom: "#ec4899",
    accentTo: "#8b5cf6",
    outcomesAr: ["تحويل تصاميم Figma إلى مواقع حية متفاعلة", "إضافة أنيميشن ناعم وتأثيرات تمرير ثلاثية الأبعاد", "ربط الدومينات المخصصة وإدارة الـ SEO التقني"],
    outcomesEn: ["Convert Figma files into live interactive websites", "Add silky scroll animations and 3D interactions", "Configure custom domains and technical SEO metadata"],
    realityAr: "أداة Framer ممتازة لمواقع الشركات والصفحات التسويقية، وليست للتطبيقات المعقدة ذات الحسابات.",
    realityEn: "Framer excels at marketing and landing sites, not database-heavy SaaS applications.",
    badgeTitleAr: "مصمم مواقع نو-كود",
    badgeTitleEn: "Framer Site Specialist",
  },
  {
    id: 20,
    slug: "custom-ecommerce-dev",
    order: 20,
    pillarId: 2,
    pillarNameAr: "البرمجة والتطوير",
    pillarNameEn: "Coding & Dev",
    titleAr: "بناء متاجر إلكترونية احترافية مخصصة",
    titleEn: "Building Custom E-Commerce Platforms",
    descriptionAr: "بناء متاجر إلكترونية سريعة تدعم سلة المشتريات، الدفع الإلكتروني، وتتبع المخزون والطلبات.",
    descriptionEn: "Develop lightning-fast online stores with shopping carts, checkout gateways, and inventory sync.",
    levelAr: "متوسط",
    levelEn: "Intermediate",
    totalLessons: 26,
    durationHours: 4.5,
    totalXp: 2500,
    icon: "🛍️",
    accentFrom: "#10b981",
    accentTo: "#047857",
    outcomesAr: ["تصميم تجربة سلة مشتريات سلسة بدون فقدان للعميل", "ربط بوابات الدفع (Stripe, Paymob, كاش)", "إدارة حالات الطلب وإشعارات الشحن التلقائية"],
    outcomesEn: ["Design high-conversion, frictionless checkout funnels", "Integrate credit cards and local mobile wallets", "Handle inventory locks and automated shipping webhooks"],
    realityAr: "المتجر الإلكتروني الناجح يقاس بسرعة تحميل صفحات المنتجات وسهولة الدفع من الموبايل.",
    realityEn: "E-commerce success hinges on checkout speed and mobile payment ease.",
    badgeTitleAr: "مطوّر تجارة إلكترونية",
    badgeTitleEn: "E-Commerce Developer",
  },

  // --- PILLAR 3: DATA ANALYTICS & BI (21-30) ---
  {
    id: 21,
    slug: "advanced-excel-powerquery",
    order: 21,
    pillarId: 3,
    pillarNameAr: "تحليل البيانات",
    pillarNameEn: "Data Analytics",
    titleAr: "إكسيل المتقدم ولوحات القيادة الذكية (Advanced Excel)",
    titleEn: "Advanced Excel & Smart Dashboards",
    descriptionAr: "تحويل الجداول التقليدية إلى لوحات تحكم تفاعلية وتقارير تنبؤية باستخدام Power Query و XLOOKUP.",
    descriptionEn: "Turn raw spreadsheets into dynamic dashboards and automated reporting models with Power Query.",
    levelAr: "مبتدئ",
    levelEn: "Beginner",
    totalLessons: 22,
    durationHours: 3.5,
    totalXp: 1800,
    icon: "📊",
    accentFrom: "#15803d",
    accentTo: "#047857",
    outcomesAr: ["إتقان دوال البحث المتقدم والتحليل الشرطي", "دمج وتنظيف آلاف الصفوف تلقائياً بـ Power Query", "تصميم لوحات مؤشرات أداء تفاعلية للمديرين"],
    outcomesEn: ["Master dynamic lookup and financial formulas", "Clean and merge massive datasets with Power Query", "Design interactive KPI dashboards for executives"],
    realityAr: "إكسيل هو الأداة الأكثر استخداماً في الشركات عالمياً؛ إتقانه يفتح أبواب الترقي فوراً.",
    realityEn: "Excel remains the corporate standard; mastering it drives immediate workplace leverage.",
    badgeTitleAr: "محترف إكسيل معتمد",
    badgeTitleEn: "Advanced Excel Analyst",
  },
  {
    id: 22,
    slug: "sql-data-analytics",
    order: 22,
    pillarId: 3,
    pillarNameAr: "تحليل البيانات",
    pillarNameEn: "Data Analytics",
    titleAr: "لغة SQL لاستخراج البيانات وقواعد القرارات",
    titleEn: "SQL for Data & Business Analytics",
    descriptionAr: "تعلم كتابة استعلامات SQL متقدمة لاستخراج التقارير وتحليل سلوك المستخدمين من قواعد البيانات.",
    descriptionEn: "Query enterprise databases, join complex tables, and extract analytical business insights with SQL.",
    levelAr: "مبتدئ",
    levelEn: "Beginner",
    totalLessons: 24,
    durationHours: 4,
    totalXp: 2100,
    icon: "🗄️",
    accentFrom: "#0284c7",
    accentTo: "#1d4ed8",
    outcomesAr: ["كتابة استعلامات دمج الجداول (Complex JOINs)", "استخدام الدوال التجميعية والنافذية (Window Functions)", "حساب معدل بقاء العملاء (Cohort & Retention Analysis)"],
    outcomesEn: ["Write multi-table relational JOIN queries", "Leverage Groupings and Analytical Window Functions", "Calculate customer retention and cohort churn metrics"],
    realityAr: "الـ SQL ليست للبرمجة بل للإجابة عن أسئلة الأعمال الحقيقية من داخل البيانات.",
    realityEn: "SQL is not about programming; it is about answering critical business questions.",
    badgeTitleAr: "محلل بيانات SQL",
    badgeTitleEn: "SQL Data Specialist",
  },
  {
    id: 23,
    slug: "powerbi-tableau-visualization",
    order: 23,
    pillarId: 3,
    pillarNameAr: "تحليل البيانات",
    pillarNameEn: "Data Analytics",
    titleAr: "تصميم لوحات المعلومات التفاعلية (Power BI)",
    titleEn: "Data Visualization with Power BI",
    descriptionAr: "بناء تقارير بصرية حية تربط مصادر بيانات متعددة وتساعد صناع القرار في قراءة الأرقام بنظرة واحدة.",
    descriptionEn: "Build live executive dashboards that combine multiple sources into actionable visual intelligence.",
    levelAr: "متوسط",
    levelEn: "Intermediate",
    totalLessons: 25,
    durationHours: 4,
    totalXp: 2200,
    icon: "📈",
    accentFrom: "#eab308",
    accentTo: "#d97706",
    outcomesAr: ["بناء نماذج البيانات (Data Modeling & Star Schema)", "كتابة مقاييس DAX الحسابية المعقدة", "تصميم شاشات تفاعلية سهلة الفهم للقيادات"],
    outcomesEn: ["Build robust Star Schema relationship models", "Write complex DAX analytical measures", "Craft intuitive executive-ready visual reports"],
    realityAr: "اللوحة الممتازة ليست المليئة بالألوان الكثيرة، بل التي توضح أين المشكلة في 5 ثوانٍ.",
    realityEn: "A great dashboard is not visually cluttered; it reveals business bottlenecks in 5 seconds.",
    badgeTitleAr: "أخصائي لوحات Power BI",
    badgeTitleEn: "Power BI Data Specialist",
  },
  {
    id: 24,
    slug: "python-data-science",
    order: 24,
    pillarId: 3,
    pillarNameAr: "تحليل البيانات",
    pillarNameEn: "Data Analytics",
    titleAr: "تحليل البيانات العملي ببايثون (Pandas & Seaborn)",
    titleEn: "Data Science with Python & Pandas",
    descriptionAr: "تنظيف، تحليل، ورسم البيانات الضخمة باستخدام مكتبات بايثون الرائدة في علم البيانات.",
    descriptionEn: "Clean, manipulate, and visualize massive datasets using Python, Pandas, and Matplotlib.",
    levelAr: "متوسط",
    levelEn: "Intermediate",
    totalLessons: 26,
    durationHours: 4.5,
    totalXp: 2400,
    icon: "🔬",
    accentFrom: "#0284c7",
    accentTo: "#6366f1",
    outcomesAr: ["معالجة البيانات المفقودة والقيم الشاذة (Outliers)", "تحليل العلاقات والارتباطات الإحصائية بين المتغيرات", "إنشاء رسوم بيانية احترافية قابلة للنشر في التقارير"],
    outcomesEn: ["Impute missing data and filter anomalous outliers", "Compute statistical correlations across features", "Export publication-grade data charts"],
    realityAr: "80% من عمل عالم البيانات هو تنظيف وتجهيز البيانات، وليس تطبيق الخوارزميات المعقدة.",
    realityEn: "80% of real data science is data cleaning and munging, not training complex models.",
    badgeTitleAr: "عالم بيانات بايثون",
    badgeTitleEn: "Python Data Scientist",
  },
  {
    id: 25,
    slug: "applied-business-statistics",
    order: 25,
    pillarId: 3,
    pillarNameAr: "تحليل البيانات",
    pillarNameEn: "Data Analytics",
    titleAr: "الإحصاء العملي لاتخاذ القرارات التجارية",
    titleEn: "Applied Business Statistics & A/B Testing",
    descriptionAr: "فهم اختبارات الفرضيات، الدلالة الإحصائية، واختبارات A/B للتأكد من نجاح التغييرات والميزات الجديدة.",
    descriptionEn: "Master hypothesis testing, p-values, and A/B test experiment design to validate product choices.",
    levelAr: "متوسط",
    levelEn: "Intermediate",
    totalLessons: 20,
    durationHours: 3.5,
    totalXp: 2000,
    icon: "📐",
    accentFrom: "#4f46e5",
    accentTo: "#4338ca",
    outcomesAr: ["تصميم اختبارات A/B ذات دلالة إحصائية مؤكدة", "تجنب الأخطاء الإحصائية الشائعة والتفسيرات المضللة", "تحديد حجم العينة المناسب للتجارب التسويقية"],
    outcomesEn: ["Design statistically sound A/B tests", "Avoid sample-ratio mismatches and false conclusions", "Determine minimum detectable effect and sample size"],
    realityAr: "الأرقام يمكن أن تخدع إذا لم تفهم كيفية جمع العينة وسياقها الإحصائي.",
    realityEn: "Data easily lies without rigorous sampling methodology and sound statistical grounding.",
    badgeTitleAr: "محلل قرارات إحصائية",
    badgeTitleEn: "Business Statistics Specialist",
  },
  {
    id: 26,
    slug: "predictive-analytics-forecasting",
    order: 26,
    pillarId: 3,
    pillarNameAr: "تحليل البيانات",
    pillarNameEn: "Data Analytics",
    titleAr: "التنبؤ وتحليل الاتجاهات السوقية (Forecasting)",
    titleEn: "Predictive Analytics & Time Series",
    descriptionAr: "استخدام السلاسل الزمنية والنماذج التنبؤية لتوقع المبيعات، الطلب على المنتجات، والميزانيات القادمة.",
    descriptionEn: "Forecast sales trends, demand fluctuations, and budget cashflows using time series models.",
    levelAr: "متقدم",
    levelEn: "Advanced",
    totalLessons: 22,
    durationHours: 4,
    totalXp: 2300,
    icon: "🔮",
    accentFrom: "#7c3aed",
    accentTo: "#6d28d9",
    outcomesAr: ["تحليل الموسمية والاتجاهات العامة (Trend & Seasonality)", "تطبيق نماذج التنبؤ البسيطة والمتقدمة (ARIMA / Prophet)", "بناء سيناريوهات (What-If Analysis) لإدارة المخاطر"],
    outcomesEn: ["Deconstruct seasonal cycles and underlying trends", "Apply forecasting models (ARIMA, Prophet)", "Simulate scenario sensitivities for executive planning"],
    realityAr: "كل النماذج التنبؤية خاطئة بدرجة ما، لكن الجيد منها مفيد جداً في الاستعداد للمستقبل.",
    realityEn: "All forecasting models are approximations, but well-tuned ones provide indispensable guidance.",
    badgeTitleAr: "أخصائي تنبؤ تحليلي",
    badgeTitleEn: "Predictive Analyst",
  },
  {
    id: 27,
    slug: "data-wrangling-pipelines",
    order: 27,
    pillarId: 3,
    pillarNameAr: "تحليل البيانات",
    pillarNameEn: "Data Analytics",
    titleAr: "تنظيف وتجهيز البيانات الضخمة (Data Wrangling)",
    titleEn: "Data Wrangling & Pipeline Preparation",
    descriptionAr: "أسرار تحويل البيانات الفوضوية والمكررة إلى جداول قياسية متسقة وجاهزة للتحليل الفوري.",
    descriptionEn: "Techniques to transform messy, inconsistent unstructured logs into pristine analytical tables.",
    levelAr: "متوسط",
    levelEn: "Intermediate",
    totalLessons: 20,
    durationHours: 3.5,
    totalXp: 2000,
    icon: "🧹",
    accentFrom: "#0d9488",
    accentTo: "#059669",
    outcomesAr: ["كشف وتصحيح الأخطاء في التواريخ والأسماء والأرقام", "توحيد مصادر البيانات غير المتجانسة", "أتمتة خطوات المعالجة لتوفير ساعات العمل اليدوي"],
    outcomesEn: ["Normalize inconsistent date stamps, phone numbers, and names", "Reconcile disparate heterogeneous datasets", "Automate transformation pipelines to eliminate manual gruntwork"],
    realityAr: "إذا دخلت بيانات غير دقيقة (Garbage In)، فالنتائج ستكون مضللة حتماً (Garbage Out).",
    realityEn: "Garbage data in will for a full year produce garbage analytical output out.",
    badgeTitleAr: "مهندس معالجة البيانات",
    badgeTitleEn: "Data Wrangling Specialist",
  },
  {
    id: 28,
    slug: "kpi-dashboards-finance",
    order: 28,
    pillarId: 3,
    pillarNameAr: "تحليل البيانات",
    pillarNameEn: "Data Analytics",
    titleAr: "مؤشرات الأداء الرئيسية والتحليل المالي للشركات",
    titleEn: "Financial Metrics & Corporate KPIs",
    descriptionAr: "قراءة وتحليل القوائم المالية، هوامش الربحية، ومؤشرات CAC و LTV لتقييم صحة المشاريع.",
    descriptionEn: "Analyze P&L statements, gross margins, CAC, and LTV to diagnose company financial health.",
    levelAr: "متوسط",
    levelEn: "Intermediate",
    totalLessons: 20,
    durationHours: 3.5,
    totalXp: 2100,
    icon: "💵",
    accentFrom: "#047857",
    accentTo: "#166534",
    outcomesAr: ["حساب تكلفة الاستحواذ على العميل (CAC) وقيمته الدائمة (LTV)", "تتبع نقطة التعادل وهوامش الأرباح الحقيقية", "صياغة تقارير مالية مفهومة للمستثمرين"],
    outcomesEn: ["Calculate unit economics: CAC, LTV, and payback windows", "Track cash burn, gross margins, and break-even points", "Communicate financial trends concisely to investors"],
    realityAr: "المبيعات تخدع، والسيولة النقدية هي الحقيقة المطلقة لبقاء أي شركة.",
    realityEn: "Revenue is vanity; cash flow and margins represent absolute survival.",
    badgeTitleAr: "محلل مالي وتجاري",
    badgeTitleEn: "Financial KPI Specialist",
  },
  {
    id: 29,
    slug: "automated-reporting-analytics",
    order: 29,
    pillarId: 3,
    pillarNameAr: "تحليل البيانات",
    pillarNameEn: "Data Analytics",
    titleAr: "أتمتة التقارير الإدارية الذاتية (Automated Reporting)",
    titleEn: "Automated Executive Reporting",
    descriptionAr: "بناء أنظمة ترسل تقارير الأداء الأسبوعية واليومية للمديرين تلقائياً على الإيميل أو سلاك.",
    descriptionEn: "Create self-running pipelines that schedule and dispatch performance reports to Slack & Email.",
    levelAr: "متوسط",
    levelEn: "Intermediate",
    totalLessons: 18,
    durationHours: 3,
    totalXp: 1900,
    icon: "🤖",
    accentFrom: "#0284c7",
    accentTo: "#0f766e",
    outcomesAr: ["ربط قواعد البيانات بأدوات إرسال التقارير التلقائية", "توليد ملفات PDF ولوحات ملخصة دون تدخل بشري", "إطلاق تنبيهات ذكية عند انخفاض المبيعات عن الحد المستهدف"],
    outcomesEn: ["Connect production data to automated reporting schedulers", "Generate automated executive PDF briefs", "Trigger instant alert pings on unusual metric drops"],
    realityAr: "الأتمتة توفر مئات الساعات، بشرط اختبار التنبيهات جيداً حتى لا ترسل أرقاماً غير صحيحة.",
    realityEn: "Automation saves hundreds of hours, provided alert criteria are verified for zero false alarms.",
    badgeTitleAr: "خبير أتمتة التقارير",
    badgeTitleEn: "Automated Reporting Specialist",
  },
  {
    id: 30,
    slug: "data-driven-decision-making",
    order: 30,
    pillarId: 3,
    pillarNameAr: "تحليل البيانات",
    pillarNameEn: "Data Analytics",
    titleAr: "التفكير القائم على البيانات لرواد الأعمال والمديرين",
    titleEn: "Data-Driven Decision Making for Leaders",
    descriptionAr: "كيف تبتعد عن التخمين وتبني قرارات التوظيف، التسعير، والتوسع على حقائق وأرقام واضحة.",
    descriptionEn: "Move past gut feelings and formulate hiring, pricing, and product strategies backed by hard data.",
    levelAr: "مبتدئ",
    levelEn: "Beginner",
    totalLessons: 18,
    durationHours: 2.5,
    totalXp: 1600,
    icon: "🎯",
    accentFrom: "#0891b2",
    accentTo: "#0e7490",
    outcomesAr: ["طرح الأسئلة الصحيحة قبل طلب أي تقرير", "تحديد المقياس الوحيد الأهم (North Star Metric)", "التفريق بين السبب والارتباط العابر (Correlation vs Causation)"],
    outcomesEn: ["Frame precise questions before commissioning reports", "Identify your company's North Star Metric", "Distinguish superficial correlation from true causation"],
    realityAr: "البيانات تقدم لك الحقائق، لكن الحكمة والخبرة هي التي تختار القرار المناسب.",
    realityEn: "Data reveals what happened; strategic wisdom decides how to capitalize on it.",
    badgeTitleAr: "قائد معتمد بالبيانات",
    badgeTitleEn: "Data-Driven Leader",
  },

  // --- PILLAR 4: FREELANCING & AGENCIES (31-40) ---
  {
    id: 31,
    slug: "zero-to-first-dollar-freelancer",
    order: 31,
    pillarId: 4,
    pillarNameAr: "العمل الحر",
    pillarNameEn: "Freelancing",
    titleAr: "إطلاق مسار الفريلانس من الصفر حتى أول دولار",
    titleEn: "Zero to First Dollar Freelancer",
    descriptionAr: "خريطة طريق عملية خطوة بخطوة لاختيار مهارتك المربحة وإغلاق أول عميل يدفع لك خلال 30 يوماً.",
    descriptionEn: "Step-by-step roadmap to package your marketable skill and sign your first paying client in 30 days.",
    levelAr: "مبتدئ",
    levelEn: "Beginner",
    totalLessons: 24,
    durationHours: 3.5,
    totalXp: 1800,
    icon: "🚀",
    accentFrom: "#f59e0b",
    accentTo: "#d97706",
    outcomesAr: ["تحديد المهارة التي يدفع الناس فيها أموالاً اليوم", "بناء نموذج عمل تجريبي يثبت جودتك بسرعة", "الحصول على أول تقييم إيجابي 5 نجوم يفتح الباب للقادم"],
    outcomesEn: ["Identify high-demand commercial skills clients pay for", "Assemble a fast proof-of-work sample portfolio", "Earn your first glowing 5-star testimonial"],
    realityAr: "العميل الأول هو الأصعب دائماً؛ بعده تصبح الثقة أسهل بمراحل.",
    realityEn: "Landing client #1 is always the hardest; subsequent clients build on proof.",
    badgeTitleAr: "مستقل مبتدئ معتمد",
    badgeTitleEn: "Certified Freelance Starter",
  },
  {
    id: 32,
    slug: "upwork-fiverr-global-mastery",
    order: 32,
    pillarId: 4,
    pillarNameAr: "العمل الحر",
    pillarNameEn: "Freelancing",
    titleAr: "احتراف منصات العمل الحر العالمية (Upwork & Fiverr)",
    titleEn: "Upwork & Global Freelance Platforms",
    descriptionAr: "أسرار تصدر نتائج البحث في Upwork وكتابة بروفايل مغناطيسي يجذب العملاء الدوليين برواتب دولارية.",
    descriptionEn: "Rank top on Upwork search and craft a magnetic profile that attracts international USD contracts.",
    levelAr: "متوسط",
    levelEn: "Intermediate",
    totalLessons: 26,
    durationHours: 4,
    totalXp: 2200,
    icon: "🌐",
    accentFrom: "#16a34a",
    accentTo: "#15803d",
    outcomesAr: ["كتابة عنوان ووصف بروفايل يحقق Top Rated بسرعة", "استراتيجية استخدام الـ Connects بدون إهدار أموال", "كيف تتجنب العملاء المحتالين ومشاكل الحسابات"],
    outcomesEn: ["Write profiles structured for Top Rated status", "Optimize Connects bidding strategy for high ROI", "Identify red-flag scam clients before submitting proposals"],
    realityAr: "المنافسة شرسة على المنصات؛ التميز يكون بالتخصص الدقيق وليس بالعمومية.",
    realityEn: "Competition is global; riches are in narrow niche specialization.",
    badgeTitleAr: "محترف منصات العمل الحر",
    badgeTitleEn: "Top-Rated Freelancer",
  },
  {
    id: 33,
    slug: "winning-proposals-cold-emailing",
    order: 33,
    pillarId: 4,
    pillarNameAr: "العمل الحر",
    pillarNameEn: "Freelancing",
    titleAr: "كتابة العروض والمقترحات البيعية الفتاكة (Proposals)",
    titleEn: "Winning Proposals & Cold Outreach",
    descriptionAr: "كيف تكتب عرض عمل (Proposal) أو إيميل يفتحه العميل ويرد عليه في أقل من 10 دقائق.",
    descriptionEn: "Craft proposals and cold outreach emails that compel clients to respond and book a call.",
    levelAr: "متوسط",
    levelEn: "Intermediate",
    totalLessons: 22,
    durationHours: 3,
    totalXp: 1900,
    icon: "✉️",
    accentFrom: "#ea580c",
    accentTo: "#c2410c",
    outcomesAr: ["صياغة أول سطرين يجبران العميل على فتح العرض كاملاً", "تقديم حل سريع لمشكلة العميل قبل أن يطلب", "نماذج وقوالب جاهزة لعشرات المجالات المهنية"],
    outcomesEn: ["Write the opening 2 lines that guarantee full reads", "Provide immediate value solutions inside the proposal", "Plug-and-play proven templates across diverse niches"],
    realityAr: "العميل لا يهتم بسيرتك الذاتية، هو يهتم فقط بما يمكنك حله لمشكلته.",
    realityEn: "Clients don't care about your resume; they only care if you can solve their problem.",
    badgeTitleAr: "خبير إغلاق الصفقات",
    badgeTitleEn: "Proposal Specialist",
  },
  {
    id: 34,
    slug: "high-ticket-pricing-packaging",
    order: 34,
    pillarId: 4,
    pillarNameAr: "العمل الحر",
    pillarNameEn: "Freelancing",
    titleAr: "تسعير الخدمات وباقات القيمة المرتفعة (High-Ticket)",
    titleEn: "High-Ticket Pricing & Packaging",
    descriptionAr: "الخروج من فخ التسعير بالساعة والانتقال إلى التسعير القائم على القيمة والنتائج (Value-Based Pricing).",
    descriptionEn: "Escape the hourly-rate trap and transition to value-based high-ticket service packages.",
    levelAr: "متوسط",
    levelEn: "Intermediate",
    totalLessons: 20,
    durationHours: 3,
    totalXp: 2000,
    icon: "💎",
    accentFrom: "#d97706",
    accentTo: "#b45309",
    outcomesAr: ["مضاعفة أسعارك 3x دون فقدان العملاء الحقيقيين", "بناء باقات متدرجة (Bronze, Silver, Gold)", "التفاوض بثقة وتقديم فواتير عالية القيمة"],
    outcomesEn: ["Triple your rates while signing higher-caliber clients", "Structure 3-tier value packages that steer choices", "Command price authority with zero awkwardness"],
    realityAr: "العملاء الذين يدفعون مبالغ أعلى هم الأقل إزعاجاً والأكثر تقديراً لعملك الاحترافي.",
    realityEn: "High-paying clients are notoriously less demanding and far more appreciative.",
    badgeTitleAr: "خبير التسعير القيمي",
    badgeTitleEn: "Value Pricing Strategist",
  },
  {
    id: 35,
    slug: "client-management-retention",
    order: 35,
    pillarId: 4,
    pillarNameAr: "العمل الحر",
    pillarNameEn: "Freelancing",
    titleAr: "إدارة وتثبيت العملاء والعقود الشهرية (Retainers)",
    titleEn: "Client Management & Monthly Retainers",
    descriptionAr: "تحويل العميل من مشروع لمرة واحدة إلى عقد شهري مستدام يضمن لك دخلاً ثابتاً يمكن التنبؤ به.",
    descriptionEn: "Convert one-off project clients into recurring monthly retainer contracts for predictable income.",
    levelAr: "متوسط",
    levelEn: "Intermediate",
    totalLessons: 22,
    durationHours: 3.5,
    totalXp: 2100,
    icon: "🤝",
    accentFrom: "#059669",
    accentTo: "#0f766e",
    outcomesAr: ["توقيع عقود احتجاز شهرية (Monthly Retainer Agreements)", "إدارة توقعات العميل لمنع تضخم نطاق العمل (Scope Creep)", "التعامل الدبلوماسي مع الخلافات والملاحظات الصعبة"],
    outcomesEn: ["Structure ongoing monthly retainer contracts", "Prevent scope creep with polite boundary agreements", "De-escalate client friction and resolve dispute revisions"],
    realityAr: "الاحتفاظ بعميل حالي أرخص 5 مرات وأسهل من البحث عن عميل جديد كل شهر.",
    realityEn: "Retaining an existing client is 5x cheaper and easier than acquiring a new one.",
    badgeTitleAr: "مدير علاقات عملاء",
    badgeTitleEn: "Client Retention Specialist",
  },
  {
    id: 36,
    slug: "portfolio-building-case-studies",
    order: 36,
    pillarId: 4,
    pillarNameAr: "العمل الحر",
    pillarNameEn: "Freelancing",
    titleAr: "بناء سابقة الأعمال ودراسات الحالة المقنعة (Portfolio)",
    titleEn: "Case-Study Driven Portfolios",
    descriptionAr: "كيف تعرض أعمالك السابقة في شكل قصص نجاح حقيقية تثبت العائد الاستثماري لخدماتك.",
    descriptionEn: "Structure portfolio case studies showing problem, solution, and measurable business ROI.",
    levelAr: "مبتدئ",
    levelEn: "Beginner",
    totalLessons: 20,
    durationHours: 3,
    totalXp: 1800,
    icon: "📂",
    accentFrom: "#4f46e5",
    accentTo: "#7c3aed",
    outcomesAr: ["صياغة دراسات حالة تركز على الأرقام والنتائج", "عرض أعمال وهمية احترافية إذا كنت لا تملك عملاء سابقين", "تصميم صفحة سابقة أعمال بسيطة ومقنعة"],
    outcomesEn: ["Write result-oriented case studies highlighting metric lifts", "Create convincing mock concept projects if starting from scratch", "Design an uncluttered, high-credibility portfolio site"],
    realityAr: "سابقة أعمال بها 3 مشاريع مدروسة ومكتوبة بعناية أفضل من 50 صورة دون سياق.",
    realityEn: "Three detailed, problem-solving case studies beat fifty uncontextualized screenshots.",
    badgeTitleAr: "مصمم سابقة أعمال",
    badgeTitleEn: "Portfolio Architect",
  },
  {
    id: 37,
    slug: "freelancer-finances-cashflow",
    order: 37,
    pillarId: 4,
    pillarNameAr: "العمل الحر",
    pillarNameEn: "Freelancing",
    titleAr: "إدارة التدفقات المالية والضرائب للفريلانسر",
    titleEn: "Freelancer Financial Planning & Taxes",
    descriptionAr: "كيف تدير دخلك المتغير، تدخر للطوارئ، وتستلم أموالك من الخارج بأقل عمولات تحويل ممكنة.",
    descriptionEn: "Manage variable freelance income, build emergency reserves, and receive international payments cheaply.",
    levelAr: "مبتدئ",
    levelEn: "Beginner",
    totalLessons: 18,
    durationHours: 2.5,
    totalXp: 1600,
    icon: "💳",
    accentFrom: "#0d9488",
    accentTo: "#15803d",
    outcomesAr: ["فتح حسابات بنكية وبطاقات دولية لاستلام الدولار واليورو", "فصل الحساب الشخصي عن حساب العمل التجاري", "حساب الميزانية الشخصية في فترات انخفاض الطلب"],
    outcomesEn: ["Set up multi-currency accounts (Wise, Payoneer) with lowest fees", "Separate personal and business finances cleanly", "Budget smoothly through unpredictable seasonal lulls"],
    realityAr: "ليس المهم كم كسبت هذا الشهر، بل كم تبقى لديك بعد المصاريف والطوارئ.",
    realityEn: "It is not what you invoice this month; it is what remains after expenses and rainy days.",
    badgeTitleAr: "خبير ماليات الفريلانس",
    badgeTitleEn: "Freelance Finance Specialist",
  },
  {
    id: 38,
    slug: "freelancer-to-agency-scaling",
    order: 38,
    pillarId: 4,
    pillarNameAr: "العمل الحر",
    pillarNameEn: "Freelancing",
    titleAr: "التحول من مستقل إلى صاحب وكالة مصغرة (Agency)",
    titleEn: "Scaling from Freelancer to Micro-Agency",
    descriptionAr: "كيف تفوض المهام التنفيذية، توظف مستقلين تحت إشرافك، وتركز فقط على المبيعات والتوسع.",
    descriptionEn: "Delegate execution tasks, hire subcontractor talent, and step into the CEO sales role.",
    levelAr: "متقدم",
    levelEn: "Advanced",
    totalLessons: 24,
    durationHours: 4,
    totalXp: 2300,
    icon: "🏢",
    accentFrom: "#b45309",
    accentTo: "#78350f",
    outcomesAr: ["بناء أنظمة تشغيل قياسية (SOPs) لتفويض المهام بسهولة", "توظيف ومتابعة المستقلين لضمان تسليم نفس جودتك", "زيادة سعة استقبال المشاريع إلى 5 أضعاف دون إرهاق"],
    outcomesEn: ["Write Standard Operating Procedures (SOPs) for turnkey delegation", "Recruit and vet quality subcontractors to replicate your output", "5x your project capacity without doubling your work hours"],
    realityAr: "الانتقال لوكالة يتطلب التخلي عن الرغبة في عمل كل شيء بيدك وقبول تفويض الآخرين.",
    realityEn: "Scaling to an agency requires letting go of perfectionism and trusting structured delegation.",
    badgeTitleAr: "مؤسس وكالة خدمات",
    badgeTitleEn: "Agency Founder",
  },
  {
    id: 39,
    slug: "global-invoicing-international-clients",
    order: 39,
    pillarId: 4,
    pillarNameAr: "العمل الحر",
    pillarNameEn: "Freelancing",
    titleAr: "استقطاب العملاء الأجانب وتحصيل الأموال عالمياً",
    titleEn: "Landing & Invoicing International Clients",
    descriptionAr: "كيف تكسر حاجز اللغة وتتحدث بثقة مع عملاء في أمريكا وأوروبا والخليج العربي برواتب مجزية.",
    descriptionEn: "Overcome language barriers and pitch US, EU, and Gulf clients confident in your global value.",
    levelAr: "متوسط",
    levelEn: "Intermediate",
    totalLessons: 22,
    durationHours: 3.5,
    totalXp: 2100,
    icon: "🌍",
    accentFrom: "#0369a1",
    accentTo: "#0284c7",
    outcomesAr: ["فهم عقلية وثقافة بيئة العمل في الأسواق الغربية والخليجية", "إصدار فواتير احترافية مطابقة للمعايير الدولية", "التواصل بالإنجليزية المهنية البسيطة الخالية من الأخطاء"],
    outcomesEn: ["Understand business etiquette across US, European, and Gulf markets", "Issue compliant international commercial invoices", "Communicate with crisp, professional business English"],
    realityAr: "العميل الأجنبي يبحث عن الأمانة والالتزام بالمواعيد أكثر من بحثه عن الإنجليزية المثالية.",
    realityEn: "International clients prioritize punctuality and reliability far above fluent prose.",
    badgeTitleAr: "مستقل دولي معتمد",
    badgeTitleEn: "Global Freelance Specialist",
  },
  {
    id: 40,
    slug: "freelance-burnout-prevention",
    order: 40,
    pillarId: 4,
    pillarNameAr: "العمل الحر",
    pillarNameEn: "Freelancing",
    titleAr: "إدارة الوقت والوقاية من الاحتراق النفسي للمستقلين",
    titleEn: "Freelance Burnout Prevention & Balance",
    descriptionAr: "كيف تضع حدوداً صارمة للعمل من المنزل، تنظم يومك، وتمنع العملاء من سرقة عطلتك الأسبوعية.",
    descriptionEn: "Set firm remote boundaries, reclaim weekends, and build a stress-resilient freelance schedule.",
    levelAr: "مبتدئ",
    levelEn: "Beginner",
    totalLessons: 18,
    durationHours: 2.5,
    totalXp: 1600,
    icon: "🧘",
    accentFrom: "#10b981",
    accentTo: "#047857",
    outcomesAr: ["وضع حدود واضحة لساعات الرد على الرسائل والاتصالات", "تصميم أسبوع عمل متوازن يحمي صحتك النفسية والجسدية", "التغلب على الشعور الدائم بالذنب عند أخذ إجازة"],
    outcomesEn: ["Enforce strict communication office hours with clients", "Design an energizing workweek protecting physical vitality", "Eliminate toxic guilt when stepping away for rest"],
    realityAr: "إذا أحرقت نفسك، فلن يستفيد عميلك ولن تتمكن من العمل غداً؛ صحتك هي رأس مالك الحقيقي.",
    realityEn: "If you burn out, you have no business tomorrow; health is your primary income asset.",
    badgeTitleAr: "مستقل متوازن ومستدام",
    badgeTitleEn: "Sustainable Freelancer",
  },

  // --- PILLAR 5: DIGITAL MARKETING & GROWTH (41-50) ---
  {
    id: 41,
    slug: "integrated-digital-marketing-strategy",
    order: 41,
    pillarId: 5,
    pillarNameAr: "التسويق الرقمي",
    pillarNameEn: "Marketing & Growth",
    titleAr: "استراتيجيات التسويق الرقمي المتكاملة للنمو",
    titleEn: "Integrated Digital Marketing Strategy",
    descriptionAr: "بناء خطة تسويقية شاملة تحدد العميل المثالي، قنوات الاستحواذ، وميزانيات الحملات الإعلانية.",
    descriptionEn: "Formulate complete acquisition funnels identifying your ideal persona and omni-channel growth mix.",
    levelAr: "مبتدئ",
    levelEn: "Beginner",
    totalLessons: 24,
    durationHours: 3.5,
    totalXp: 1900,
    icon: "🎯",
    accentFrom: "#f43f5e",
    accentTo: "#e11d48",
    outcomesAr: ["تحديد شخصية العميل المشتري (Buyer Persona) بدقة", "اختيار القنوات الإعلانية الأنسب لميزانيتك", "توزيع الميزانية بين الوعي بالبراند والمبيعات المباشرة"],
    outcomesEn: ["Profile high-converting buyer personas", "Select optimal marketing channels for maximum ROI", "Balance brand awareness and direct-response performance ad budgets"],
    realityAr: "التسويق بدون دراسة واضحة لجمهورك هو حرق مباشر للأموال دون فائدة.",
    realityEn: "Marketing without clear customer validation is simply burning ad dollars.",
    badgeTitleAr: "استراتيجي تسويق رقمي",
    badgeTitleEn: "Digital Marketing Strategist",
  },
  {
    id: 42,
    slug: "meta-ads-mastery",
    order: 42,
    pillarId: 5,
    pillarNameAr: "التسويق الرقمي",
    pillarNameEn: "Marketing & Growth",
    titleAr: "احتراف إعلانات الميتا (Facebook & Instagram Ads)",
    titleEn: "Meta Ads Mastery: Facebook & Instagram",
    descriptionAr: "إطلاق حملات إعلانية مربحة على فيسبوك وإنستجرام باستخدام استراتيجيات التوسع وتتبع الـ Pixel و CAPI.",
    descriptionEn: "Launch profitable Facebook and Instagram ad campaigns using scaling frameworks and Pixel/CAPI tracking.",
    levelAr: "متوسط",
    levelEn: "Intermediate",
    totalLessons: 26,
    durationHours: 4,
    totalXp: 2200,
    icon: "📱",
    accentFrom: "#2563eb",
    accentTo: "#1d4ed8",
    outcomesAr: ["إعداد وتدريب خوارزمية Meta Pixel و Conversions API", "اختبار الإبداع الإعلاني (Creative Testing Frameworks)", "توسيع الحملات الناجحة أفقياً ورأسياً (Scaling Ads)"],
    outcomesEn: ["Configure and train Meta Pixel & Server-Side Conversions API", "Execute scientific creative testing matrices", "Scale winning ad sets horizontally and vertically"],
    realityAr: "نجاح إعلانات ميتا اليوم يعتمد 80% على جودة الفيديو والصورة (Creative)، و20% فقط على الاستهداف.",
    realityEn: "Meta ad success is 80% creative angle/hook quality and 20% audience targeting.",
    badgeTitleAr: "محترف إعلانات ميتا",
    badgeTitleEn: "Meta Media Buyer",
  },
  {
    id: 43,
    slug: "google-ads-performance-max",
    order: 43,
    pillarId: 5,
    pillarNameAr: "التسويق الرقمي",
    pillarNameEn: "Marketing & Growth",
    titleAr: "إعلانات جوجل وشبكات البحث (Google Ads & PMax)",
    titleEn: "Google Search Ads & Performance Max",
    descriptionAr: "كيف تظهر في النتيجة الأولى عند بحث العميل المستعد للشراء فوراً على محرك بحث جوجل.",
    descriptionEn: "Capture high-intent ready-to-buy search traffic on Google Search, Shopping, and Performance Max.",
    levelAr: "متوسط",
    levelEn: "Intermediate",
    totalLessons: 24,
    durationHours: 4,
    totalXp: 2100,
    icon: "🔍",
    accentFrom: "#ea4335",
    accentTo: "#c5221f",
    outcomesAr: ["اختيار الكلمات المفتاحية ذات نية الشراء العالية (High Intent)", "كتابة إعلانات بحث ترفع نسبة النقر (CTR)", "تحسين حملات Performance Max لخفض تكلفة العميل"],
    outcomesEn: ["Select high-intent transactional search keywords", "Craft search ad copy driving 8%+ click-through rates", "Optimize Performance Max asset groups for low CPA"],
    realityAr: "إعلانات جوجل تستهدف أشخاصاً يبحثون عن الحل بالفعل، بينما منصات التواصل توقظ رغبة الشراء.",
    realityEn: "Google ads target active intent; social media interrupts and stimulates passive desire.",
    badgeTitleAr: "أخصائي إعلانات جوجل",
    badgeTitleEn: "Google Ads Specialist",
  },
  {
    id: 44,
    slug: "tiktok-ads-viral-marketing",
    order: 44,
    pillarId: 5,
    pillarNameAr: "التسويق الرقمي",
    pillarNameEn: "Marketing & Growth",
    titleAr: "إعلانات تيك توك وصناعة المحتوى الفيروسي",
    titleEn: "TikTok Ads & Viral Video Marketing",
    descriptionAr: "أسرار خوارزمية تيك توك، صناعة فيديوهات UGC حقيقية، وتحقيق مبيعات ضخمة بتكلفة نقرة منخفضة.",
    descriptionEn: "Crack the TikTok algorithm with native UGC creative concepts that convert at low cost-per-click.",
    levelAr: "مبتدئ",
    levelEn: "Beginner",
    totalLessons: 22,
    durationHours: 3,
    totalXp: 1800,
    icon: "🎵",
    accentFrom: "#000000",
    accentTo: "#00f2fe",
    outcomesAr: ["تصميم إعلانات تبدو كمحتوى طبيعي وليس إعلاناً تقليدياً", "التعاون مع صناع المحتوى المؤثرين لإنتاج UGC", "استخدام TikTok Spark Ads لتعزيز الفيديوهات الناجحة"],
    outcomesEn: ["Produce native-feel ad videos that bypass banner blindness", "Partner with micro-creators for authentic UGC assets", "Leverage TikTok Spark Ads to amplify viral momentum"],
    realityAr: "المستخدم على تيك توك يمرر بإصبعه كل ثانية؛ إذا لم تشده في أول ثانيتين، فقدته تماماً.",
    realityEn: "TikTok users swipe every second; miss the first 2-second hook and your budget is lost.",
    badgeTitleAr: "محترف إعلانات تيك توك",
    badgeTitleEn: "TikTok Growth Specialist",
  },
  {
    id: 45,
    slug: "modern-seo-semantic-search",
    order: 45,
    pillarId: 5,
    pillarNameAr: "التسويق الرقمي",
    pillarNameEn: "Marketing & Growth",
    titleAr: "تحسين محركات البحث وتصدر النتائج (Modern SEO)",
    titleEn: "Modern SEO & Semantic Search",
    descriptionAr: "تصدر نتائج محركات البحث والحصول على آلاف الزوار المجانيين يومياً دون دفع سنت واحد للإعلانات.",
    descriptionEn: "Rank #1 on Google organically and drive thousands of qualified free visitors every day.",
    levelAr: "متوسط",
    levelEn: "Intermediate",
    totalLessons: 25,
    durationHours: 4,
    totalXp: 2200,
    icon: "🌐",
    accentFrom: "#059669",
    accentTo: "#047857",
    outcomesAr: ["بناء بنية موقع متوافقة مع الـ Semantic Search والـ AI", "كتابة مقالات تكتسح الكلمات المفتاحية التنافسية", "بناء الروابط الخلفية القوية (Backlinks) بأساليب آمنة"],
    outcomesEn: ["Structure websites for semantic entity search and AI Overviews", "Produce comprehensive topical cluster content that ranks", "Execute ethical, high-domain-authority backlink outreach"],
    realityAr: "الـ SEO ماراثون طويل يستغرق أشهراً ليثمر، ولكنه الأصل الأكثر قيمة وديمومة لأي موقع.",
    realityEn: "SEO is a multi-month compounding marathon, yet builds the highest-margin sustainable asset.",
    badgeTitleAr: "خبير تصدر نتائج البحث",
    badgeTitleEn: "SEO Master",
  },
  {
    id: 46,
    slug: "high-converting-copywriting",
    order: 46,
    pillarId: 5,
    pillarNameAr: "التسويق الرقمي",
    pillarNameEn: "Marketing & Growth",
    titleAr: "كتابة النصوص الإعلانية والإقناعية (Copywriting)",
    titleEn: "High-Converting Sales Copywriting",
    descriptionAr: "سيكولوجيا الكلمات التي تدفع القارئ لإخراج بطاقته الائتمانية والشراء باقتناع ورغبة حقيقية.",
    descriptionEn: "Master the psychology of persuasive sales copy that compels readers to take immediate buying action.",
    levelAr: "مبتدئ",
    levelEn: "Beginner",
    totalLessons: 22,
    durationHours: 3.5,
    totalXp: 1900,
    icon: "✍️",
    accentFrom: "#dc2626",
    accentTo: "#991b1b",
    outcomesAr: ["استخدام معادلات الكتابة الشهيرة (AIDA, PAS, FAB)", "تحويل الميزات الجافة إلى فوائد ملموسة تلمس حياة المشتري", "كتابة نداءات شراء (CTAs) لا يمكن مقاومتها"],
    outcomesEn: ["Apply proven copy frameworks: PAS, AIDA, and StoryBrand", "Translate technical specs into emotion-stirring tangible benefits", "Write compelling call-to-actions that trigger immediate clicks"],
    realityAr: "النص العظيم لا يصرخ، بل يتحدث بصوت هادئ ومقنع يطابق الحوار الدائر في عقل العميل.",
    realityEn: "Great copy doesn't yell; it enters the precise ongoing conversation inside the customer's mind.",
    badgeTitleAr: "كاتب نصوص إعلانية محترف",
    badgeTitleEn: "Sales Copywriter",
  },
  {
    id: 47,
    slug: "sales-funnels-cro",
    order: 47,
    pillarId: 5,
    pillarNameAr: "التسويق الرقمي",
    pillarNameEn: "Marketing & Growth",
    titleAr: "قمع المبيعات ومضاعفة معدل التحويل (Funnels & CRO)",
    titleEn: "Sales Funnels & Conversion Optimization",
    descriptionAr: "كيف تضاعف مبيعات موقعك الحالي من نفس عدد الزوار عبر تحسين تجربة صفحة الهبوط وإزالة العوائق.",
    descriptionEn: "Double your revenue from existing web traffic by optimizing landing page friction and sales funnels.",
    levelAr: "متوسط",
    levelEn: "Intermediate",
    totalLessons: 24,
    durationHours: 3.5,
    totalXp: 2100,
    icon: "🌪️",
    accentFrom: "#d97706",
    accentTo: "#b45309",
    outcomesAr: ["تحليل خرائط الحرارة وسلوك الزوار (Hotjar Heatmaps)", "إزالة أسباب التردد والتسرب في صفحة الدفع", "إضافة عروض الـ Order Bump و Upsells لرفع متوسط الفاتورة"],
    outcomesEn: ["Diagnose visitor drop-offs using heatmaps and screen recordings", "Eliminate checkout friction and cart abandonment hurdles", "Implement 1-click upsells and order bumps to surge average order value"],
    realityAr: "رفع معدل التحويل من 1% إلى 2% يعني مضاعفة أرباح عملك بالكامل دون زيادة ميزانية الإعلانات.",
    realityEn: "Lifting conversion from 1% to 2% doubles company profits with zero extra ad spend.",
    badgeTitleAr: "أخصائي تحسين التحويل",
    badgeTitleEn: "CRO & Funnel Architect",
  },
  {
    id: 48,
    slug: "email-marketing-automation",
    order: 48,
    pillarId: 5,
    pillarNameAr: "التسويق الرقمي",
    pillarNameEn: "Marketing & Growth",
    titleAr: "التسويق عبر البريد الإلكتروني وأتمتة الرسائل",
    titleEn: "Email Marketing & Automation",
    descriptionAr: "بناء قائمة بريدية تجلب لك مبيعات يومية متكررة دون الاعتماد على مزاج خوارزميات السوشيال ميديا.",
    descriptionEn: "Build a responsive email list generating daily repeat sales independently of changing social algorithms.",
    levelAr: "متوسط",
    levelEn: "Intermediate",
    totalLessons: 20,
    durationHours: 3,
    totalXp: 1800,
    icon: "📬",
    accentFrom: "#7c3aed",
    accentTo: "#6d28d9",
    outcomesAr: ["إعداد سلاسل الترحيب التلقائية (Welcome Sequences)", "استرداد السلات المتروكة بإيميلات مقنعة", "تقسيم القائمة البريدية (Segmentation) لرفع نسب الفتح فوق 40%"],
    outcomesEn: ["Build automated nurture and welcome sequences", "Recover abandoned carts with high-converting automated emails", "Segment subscribers to maintain 40%+ open rates"],
    realityAr: "القائمة البريدية هي القناة التسويقية الوحيدة التي تملكها بالكامل ولا يستطيع أحد حظرها عنك.",
    realityEn: "Your email list is the only customer asset you truly own and control 100%.",
    badgeTitleAr: "خبير التسويق بالإيميل",
    badgeTitleEn: "Email Growth Specialist",
  },
  {
    id: 49,
    slug: "inbound-organic-content",
    order: 49,
    pillarId: 5,
    pillarNameAr: "التسويق الرقمي",
    pillarNameEn: "Marketing & Growth",
    titleAr: "التسويق بالمحتوى الجذاب (Inbound Marketing)",
    titleEn: "Inbound & Organic Content Marketing",
    descriptionAr: "صناعة محتوى يثقف العميل ويبني معه علاقة ثقة عميقة تجعله يطلب الشراء منك دون الحاجة لإلحاح.",
    descriptionEn: "Create magnetic educational content that builds trust and turns curious followers into eager buyers.",
    levelAr: "مبتدئ",
    levelEn: "Beginner",
    totalLessons: 22,
    durationHours: 3,
    totalXp: 1800,
    icon: "🧲",
    accentFrom: "#0284c7",
    accentTo: "#0369a1",
    outcomesAr: ["بناء تقويم محتوى شهري منسق ومنتظم", "صناعة أدلة مجانية (Lead Magnets) تجذب العملاء الجادين", "تحويل المتابعين المعجبين إلى عملاء مستمرين"],
    outcomesEn: ["Architect an evergreen 30-day multi-platform editorial calendar", "Build irresistible Lead Magnets capturing qualified prospects", "Guide audience gracefully from education to paid offers"],
    realityAr: "المحتوى القوي يحتاج استمرارية؛ النتائج الملموسة تبدأ في التراكم بعد 60 يوماً من النشر المنضبط.",
    realityEn: "Content marketing compounds exponentially after 60 days of consistent, valuable delivery.",
    badgeTitleAr: "استراتيجي تسويق بالمحتوى",
    badgeTitleEn: "Inbound Content Specialist",
  },
  {
    id: 50,
    slug: "personal-branding-linkedin-x",
    order: 50,
    pillarId: 5,
    pillarNameAr: "التسويق الرقمي",
    pillarNameEn: "Marketing & Growth",
    titleAr: "بناء العلامة الشخصية وصناعة الفرص (Personal Branding)",
    titleEn: "Personal Branding on LinkedIn & X",
    descriptionAr: "كيف تبني سمعة مهنية قوية تجعل عروض العمل، الاستشارات، والشراكات تأتيك بدلاً من أن تبحث عنها.",
    descriptionEn: "Build professional authority on LinkedIn and X that attracts inbound job offers, deals, and partnerships.",
    levelAr: "مبتدئ",
    levelEn: "Beginner",
    totalLessons: 20,
    durationHours: 2.5,
    totalXp: 1700,
    icon: "🌟",
    accentFrom: "#0a66c2",
    accentTo: "#004182",
    outcomesAr: ["تحسين بروفايل LinkedIn ليصبح صفحة هبوط شخصية", "كتابة منشورات تشاركية تحقق آلاف المشاهدات أسبوعياً", "التشبيك مع قادة الصناعة وبناء شبكة علاقات استراتيجية"],
    outcomesEn: ["Transform your LinkedIn profile into a magnetic personal sales page", "Write viral thought-leadership posts commanding thousands of impressions", "Direct-message industry leaders and forge strategic relationships"],
    realityAr: "علامتك الشخصية هي ما يقوله الناس عنك حين تغادر الغرفة؛ ابدأ في بنائها اليوم قبل أن تحتاجها.",
    realityEn: "Your personal brand is what people say when you leave the room; build it before you need it.",
    badgeTitleAr: "خبير العلامة الشخصية",
    badgeTitleEn: "Personal Brand Strategist",
  },
];
